import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    isRTL: boolean;
    formatCurrency: (amount: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// English translations
const en: Record<string, string> = {
    // Header
    'header.deliverTo': 'Deliver to',
    'header.location': 'Cairo & Giza',
    'header.searchPlaceholder': 'Search products...',
    'header.all': 'All',
    'header.hello': 'Hello',
    'header.signIn': 'sign in',
    'header.accountAndLists': 'Account & Lists',
    'header.alerts': 'Alerts',
    'header.cart': 'Cart',
    'header.todaysDeals': "Today's Deals",
    'header.customerService': 'Customer Service',
    'header.registry': 'Registry',
    'header.giftCards': 'Gift Cards',
    'header.sell': 'Sell',
    'header.home': 'Home',
    'header.browseProducts': 'Browse Products',
    'header.signOut': 'Sign Out',
    'header.createAccount': 'Create Account',
    'header.departments': 'Departments',
    'header.adminDashboard': 'Admin Dashboard',
    'header.newCustomer': 'New customer?',
    'header.createNewAccount': 'Create new account',
    'header.yourAccount': 'Your Account',
    'header.yourOrders': 'Your Orders',
    'header.yourLists': 'Your Lists',

    // Categories
    'category.pcs': 'PCs',
    'category.laptops': 'Laptops',
    'category.mice': 'Mice',
    'category.keyboards': 'Keyboards',
    'category.headphones': 'Headphones',
    'category.cables': 'Cables',
    'category.mousePads': 'Mouse Pads',
    'category.hardDrives': 'Hard Drives',
    'category.books': 'Books',
    'category.fashion': 'Fashion',
    'category.homeKitchen': 'Home & Kitchen',

    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInToAccount': 'Sign in to your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.signingIn': 'Signing in...',
    'auth.newCustomer': 'New customer?',
    'auth.createAccount': 'Create account',
    'auth.emailVerified': 'Email verified! You can now sign in.',
    'auth.createYourAccount': 'Create Your Account',
    'auth.joinUs': 'Join us today',
    'auth.name': 'Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.creatingAccount': 'Creating account...',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signInHere': 'Sign in here',

    // Home Page
    'home.shopByCategory': 'Shop by Category',
    'home.viewAll': 'View all',
    'home.dealsOfTheDay': 'Deals of the Day',
    'home.seeAllDeals': 'See all deals',
    'home.inspiredByHistory': 'Inspired by your browsing history',
    'home.trendingInElectronics': 'Trending in Electronics',
    'home.signUpForBestExperience': 'Sign up for the best experience',
    'home.signUp': 'Sign Up',
    'home.pcAccessories': 'PC Accessories & Peripherals',
    'home.topRatedProducts': 'Top Rated Products',

    // Product
    'product.addToCart': 'Add to Cart',
    'product.buyNow': 'Buy Now',
    'product.inStock': 'In Stock',
    'product.outOfStock': 'Out of Stock',
    'product.prime': 'Prime',
    'product.freeDelivery': 'FREE Delivery',
    'product.quantity': 'Quantity',
    'product.reviews': 'reviews',
    'product.rating': 'rating',
    'product.price': 'Price',
    'product.originalPrice': 'Original Price',
    'product.savings': 'You Save',
    'product.description': 'Description',
    'product.specifications': 'Specifications',
    'product.customerReviews': 'Customer Reviews',

    // Cart
    'cart.shoppingCart': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.subtotal': 'Subtotal',
    'cart.items': 'items',
    'cart.proceedToCheckout': 'Proceed to Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.remove': 'Remove',
    'cart.price': 'Price',
    'cart.qty': 'Qty',

    // Checkout
    'checkout.secureCheckout': 'Secure Checkout',
    'checkout.checkout': 'Checkout',
    'checkout.shippingAddress': 'Shipping address',
    'checkout.paymentMethod': 'Payment method',
    'checkout.reviewOrder': 'Review items and shipping',
    'checkout.fullName': 'Full Name',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.state': 'State',
    'checkout.zipCode': 'ZIP Code',
    'checkout.phone': 'Phone Number',
    'checkout.continueToPayment': 'Continue to payment',
    'checkout.change': 'Change',
    'checkout.creditCard': 'Credit or debit card',
    'checkout.paypal': 'PayPal',
    'checkout.giftCard': 'Gift Card',
    'checkout.cardNumber': 'Card number',
    'checkout.nameOnCard': 'Name on card',
    'checkout.expirationDate': 'Expiration date',
    'checkout.securityCode': 'Security code',
    'checkout.continue': 'Continue',
    'checkout.shippingSpeed': 'Choose your shipping speed:',
    'checkout.freeDelivery': 'FREE Delivery',
    'checkout.standardDelivery': 'Standard Delivery',
    'checkout.expressDelivery': 'Express Delivery',
    'checkout.arrives': 'Arrives',
    'checkout.tomorrow': 'Tomorrow',
    'checkout.itemsInOrder': 'Items in your order:',
    'checkout.placeOrder': 'Place your order',
    'checkout.orderSummary': 'Order Summary',
    'checkout.shippingHandling': 'Shipping & handling',
    'checkout.estimatedTax': 'Estimated tax',
    'checkout.orderTotal': 'Order total',
    'checkout.free': 'FREE',
    'checkout.agreeTerms': 'By placing your order, you agree to our privacy notice and conditions of use.',

    // Order Confirmation
    'confirmation.orderPlaced': 'Order Placed Successfully!',
    'confirmation.thankYou': 'Thank you for your order!',
    'confirmation.emailConfirmation': 'You will receive an email confirmation shortly.',
    'confirmation.orderDetails': 'Order Details',
    'confirmation.orderNumber': 'Order Number',
    'confirmation.orderDate': 'Order Date',
    'confirmation.estimatedDelivery': 'Estimated Delivery',
    'confirmation.viewOrders': 'View Orders',

    // Footer
    'footer.getToKnowUs': 'Get to Know Us',
    'footer.aboutUs': 'About Us',
    'footer.careers': 'Careers',
    'footer.pressReleases': 'Press Releases',
    'footer.makeMoneyWithUs': 'Make Money with Us',
    'footer.sellOnShop': 'Sell on Shop',
    'footer.becomeAffiliate': 'Become an Affiliate',
    'footer.advertiseProducts': 'Advertise Your Products',
    'footer.paymentProducts': 'Payment Products',
    'footer.shopCard': 'Shop Card',
    'footer.currencyConverter': 'Shop Currency Converter',
    'footer.letUsHelpYou': 'Let Us Help You',
    'footer.returnsCenter': 'Returns Center',
    'footer.help': 'Help',
    'footer.copyright': '© 2026 Shop.com, Inc. or its affiliates',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.apply': 'Apply',
    'common.clear': 'Clear',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.signInRequired': 'Please sign in to continue checkout',

    // Customer Service
    'customerService.title': 'Customer Service',
    'customerService.howCanWeHelp': 'How can we help you?',

    // Gift Cards
    'giftCards.title': 'Gift Cards',
    'giftCards.subtitle': 'Give the perfect gift',

    // Registry
    'registry.title': 'Registry',
    'registry.subtitle': 'Create and manage your registries',

    // Sell
    'sell.title': 'Sell on Shop',
    'sell.subtitle': 'Start selling your products today',

    // Orders
    'orders.title': 'Your Orders',
    'orders.noOrders': 'You have no orders yet',

    // Account
    'account.title': 'Your Account',
    'account.settings': 'Account Settings',

    // Lists
    'lists.title': 'Your Lists',
    'lists.noLists': 'You have no lists yet',
    'lists.createList': 'Create a List',

    // Admin Panel
    'admin.overview': 'Admin Overview',
    'admin.categories': 'Categories',
    'admin.products': 'Products',
    'admin.suppliers': 'Suppliers',
    'admin.customers': 'Customers',
    'admin.orders': 'Orders',
    'admin.financial': 'Management Financial',
    'admin.homeLayout': 'Home Layout',
    'admin.files': 'Files',
    'admin.dashboard': 'Dashboard',
    'admin.navMenu': 'Navigation Menu',
    'admin.store': 'Store',
    'admin.exit': 'Exit',
    'admin.loading': 'Loading admin panel...',
    'admin.liveUpdate': 'Live Update Applied',
    
    // Admin Dashboard
    'admin.totalOrders': 'Total Orders',
    'admin.totalRevenue': 'Total Revenue',
    'admin.totalProducts': 'Total Products',
    'admin.totalCustomers': 'Total Customers',
    'admin.recentOrders': 'Recent Orders',
    'admin.recentActivity': 'Recent Activity',
    'admin.salesOverview': 'Sales Overview',
    'admin.viewAll': 'View All',
    'admin.newOrder': 'New order',
    'admin.noRecentOrders': 'No recent orders',
    'admin.noRecentActivity': 'No recent activity',
    
    // Admin Products
    'admin.addProduct': 'Add Product',
    'admin.editProduct': 'Edit Product',
    'admin.productName': 'Product Name',
    'admin.productPrice': 'Price',
    'admin.productStock': 'Stock',
    'admin.productCategory': 'Category',
    'admin.productSupplier': 'Supplier',
    'admin.productDescription': 'Description',
    'admin.productImage': 'Product Image',
    'admin.originalPrice': 'Original Price',
    'admin.costPrice': 'Cost Price',
    'admin.deleteProduct': 'Delete Product',
    'admin.confirmDelete': 'Are you sure you want to delete this?',
    
    // Admin Categories
    'admin.addCategory': 'Add Category',
    'admin.editCategory': 'Edit Category',
    'admin.categoryName': 'Category Name',
    'admin.categoryImage': 'Category Image',
    'admin.parentCategory': 'Parent Category',
    'admin.noParent': 'No Parent (Top Level)',
    
    // Admin Orders
    'admin.orderId': 'Order ID',
    'admin.customer': 'Customer',
    'admin.status': 'Status',
    'admin.date': 'Date',
    'admin.amount': 'Amount',
    'admin.pending': 'Pending',
    'admin.processing': 'Processing',
    'admin.shipped': 'Shipped',
    'admin.delivered': 'Delivered',
    'admin.cancelled': 'Cancelled',
    'admin.orderDetails': 'Order Details',
    'admin.updateStatus': 'Update Status',
    
    // Admin Suppliers
    'admin.addSupplier': 'Add Supplier',
    'admin.editSupplier': 'Edit Supplier',
    'admin.supplierName': 'Supplier Name',
    'admin.contactName': 'Contact Name',
    'admin.phone': 'Phone',
    'admin.addressLine': 'Address',
    
    // Admin Users/Customers
    'admin.userId': 'User ID',
    'admin.userName': 'Name',
    'admin.userEmail': 'Email',
    'admin.role': 'Role',
    'admin.joinedDate': 'Joined',
    
    // Admin Financial
    'admin.revenue': 'Revenue',
    'admin.expenses': 'Expenses',
    'admin.netProfit': 'Net Profit',
    'admin.taxAmount': 'Tax Amount',
    'admin.currentCycle': 'Current Cycle',
    'admin.pastCycles': 'Past Cycles',
    'admin.addExpense': 'Add Expense',
    'admin.closeCycle': 'Close Cycle',
    
    // Admin Home Layout
    'admin.homeLayoutTitle': 'Home Layout Settings',
    'admin.sectionEnabled': 'Enabled',
    'admin.sectionName': 'Section Name',
    'admin.showBadge': 'Show Badge',
    'admin.badgeText': 'Badge Text',
    'admin.manualSelection': 'Manual Selection',
    'admin.automaticSelection': 'Automatic Selection',
    'admin.selectProducts': 'Select Products',
    'admin.saveChanges': 'Save Changes',
    'admin.resetToDefault': 'Reset to Default',
    
    // Admin Files
    'admin.uploadFile': 'Upload File',
    'admin.fileName': 'File Name',
    'admin.fileSize': 'Size',
    'admin.fileType': 'Type',
    'admin.uploadDate': 'Upload Date',
    'admin.copyUrl': 'Copy URL',
    'admin.deleteFile': 'Delete',
    
    // Common Admin
    'admin.actions': 'Actions',
    'admin.noResults': 'No results found',
    'admin.searchPlaceholder': 'Search...',
    'admin.itemsPerPage': 'Items per page',
    'admin.showing': 'Showing',
    'admin.of': 'of',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.create': 'Create',
    'admin.update': 'Update',
    'admin.delete': 'Delete',
    'admin.edit': 'Edit',
    'admin.view': 'View',
    'admin.back': 'Back',
    
    // Admin Suppliers (extended)
    'admin.suppliersTitle': 'Suppliers',
    'admin.suppliersSubtitle': 'Manage your product suppliers and vendors',
    'admin.totalSuppliers': 'Total Suppliers',
    'admin.searchSuppliers': 'Search suppliers...',
    'admin.noSuppliersYet': 'No suppliers yet',
    'admin.noSuppliersFound': 'No suppliers found',
    'admin.addFirstSupplier': 'Add your first supplier to get started',
    'admin.tryAdjustSearch': 'Try adjusting your search',
    'admin.createSupplier': 'Create Supplier',
    'admin.updateSupplier': 'Update Supplier',
    'admin.supplierNameRequired': 'Supplier Name *',
    'admin.contactPerson': 'Contact Person',
    'admin.loadingSuppliers': 'Loading suppliers...',
    'admin.noContactInfo': 'No contact information',
    
    // Admin Users (extended)
    'admin.userManagement': 'User Management',
    'admin.userManagementSubtitle': 'Manage customers and administrators',
    'admin.totalUsers': 'Total Users',
    'admin.administrators': 'Administrators',
    'admin.searchUsers': 'Search users...',
    'admin.allUsers': 'All Users',
    'admin.admins': 'Admins',
    'admin.user': 'User',
    'admin.contact': 'Contact',
    'admin.location': 'Location',
    'admin.noUsersFound': 'No users found',
    'admin.tryAdjustFilters': 'Try adjusting your search or filter criteria',
    'admin.editUserProfile': 'Edit User Profile',
    'admin.fullName': 'Full Name',
    'admin.phoneNumber': 'Phone Number',
    'admin.address': 'Address',
    'admin.userRole': 'User Role',
    'admin.administrator': 'Administrator',
    'admin.loadingUsers': 'Loading users...',
    'admin.unnamedUser': 'Unnamed User',
    
    // Admin Financial (extended)
    'admin.financialManagement': 'Financial Management',
    'admin.financialSubtitle': 'Manage cycles, expenses, and track your profitability.',
    'admin.exportReport': 'Export Report',
    'admin.startNewCycle': 'Start New Cycle',
    'admin.newExpense': 'New Expense',
    'admin.activeCycle': 'Active Cycle',
    'admin.noActiveCycle': 'No Active Cycle',
    'admin.toPresent': 'to Present',
    'admin.currentRevenue': 'Current Revenue',
    'admin.currentExpenses': 'Current Expenses',
    'admin.estimatedTax': 'Estimated Tax',
    'admin.payouts': 'Payouts',
    'admin.analysis': 'Analysis',
    'admin.recentTransactions': 'Recent Transactions',
    'admin.viewAllTransactions': 'View All',
    'admin.expenseLog': 'Expense Log',
    'admin.expenseLogDesc': 'Detailed view of all operational expenses.',
    'admin.loadExpenseDashboard': 'Load Expense Dashboard',
    'admin.supplierPayouts': 'Supplier Payouts',
    'admin.supplierPayoutsDesc': 'Manage and approve payments to product suppliers.',
    'admin.viewPayoutStatus': 'View Payout Status',
    'admin.previousCycles': 'Previous Cycles',
    'admin.profit': 'Profit',
    'admin.rev': 'Rev',
    'admin.viewAllHistory': 'View All History',
    'admin.cycleControls': 'Cycle Controls',
    'admin.closeCurrentCycle': 'Close Current Cycle',
    'admin.financialProjection': 'Financial Projection',
    'admin.manageTaxSlabs': 'Manage Tax Slabs',
    'admin.loadingFinancial': 'Loading financial records...',
    'admin.margin': 'Margin',
    
    // Admin Categories Page
    'admin.availableCategories': 'Available Categories',
    'admin.totalCategories': 'Total Categories',
    'admin.withProducts': 'With Products',
    'admin.empty': 'Empty',
    'admin.noDescription': 'No description',
    'admin.noCategoriesFound': 'No categories found',
    'admin.tryAdjustingSearch': 'Try adjusting your search terms',
    'admin.getStartedCategories': 'Get started by adding your first category',
    'admin.addFirstCategory': 'Add First Category',
    'admin.deleteCategory': 'Delete Category',
    'admin.deleteCategoryConfirm': 'Are you sure you want to delete this category? Products in this category will become uncategorized.',
    'admin.categoryNameRequired': 'Name *',
    'admin.nameInEnglish': 'Name in English',
    'admin.nameInArabic': 'Name in Arabic',
    'admin.selectCategory': 'Select a category...',
    'admin.optionalDescription': 'Optional description',
    'admin.chooseFile': 'Choose File',
    'admin.takePhoto': 'Take Photo',
    'admin.pasteImageUrl': 'Or paste an image URL:',
    
    // Admin Home Layout (extended)
    'admin.visibilityControl': 'Visibility Control',
    'admin.visibilityControlDesc': 'Use the toggles below to hide or show specific sections on your main page. This is useful for clearing space during specific sales or removing sections if they have no products yet.',
    'admin.countdownBadge': 'Countdown Badge',
    'admin.manualProductSelection': 'Manual Product Selection',
    'admin.enabled': 'ENABLED',
    'admin.disabled': 'DISABLED',
    'admin.manual': 'MANUAL',
    'admin.automatic': 'AUTOMATIC',
    'admin.selectProductsToFeature': 'Select specific products to feature in this section.',
    'admin.selectProductsForBrowsing': 'Select specific products to show as browsing recommendations.',
    'admin.selectProductsForTrending': 'Select specific products to show as trending.',
    'admin.selectProductsForAccessories': 'Select specific products to show as PC accessories.',
    'admin.searchProducts': 'Search products...',
    'admin.noProductsFound': 'No products found',
    'admin.autoShowsDiscounted': 'Automatically shows all products with a discount (original price > current price).',
    'admin.autoShowsFirst10': 'Automatically shows the first 10 products as recommendations.',
    'admin.autoShowsOver50': 'Automatically shows products priced over E£50.',
    'admin.autoShowsPeripherals': 'Automatically shows products with category containing mouse, keyboard, or headphone.',
    'admin.subtitleText': 'Subtitle Text',
    'admin.buttonText': 'Button Text',
    'admin.visible': 'VISIBLE',
    'admin.hidden': 'HIDDEN',
    'admin.autoSyncingReady': 'Auto-Syncing Ready',
    'admin.realTimeUpdates': 'Real-time Updates',
    'admin.versioning': 'Versioning',
    'admin.sectionDescription': 'Section Description',
    'admin.enterBadgeText': 'Enter badge text (e.g. Ends in 12:34:56)',
    'admin.enterSubtitleText': 'Enter subtitle text',
    'admin.enterButtonText': 'Enter button text',
};

// Arabic translations
const ar: Record<string, string> = {
    // Header
    'header.deliverTo': 'التوصيل إلى',
    'header.location': 'القاهرة والجيزة',
    'header.searchPlaceholder': 'ابحث عن المنتجات...',
    'header.all': 'الكل',
    'header.hello': 'مرحباً',
    'header.signIn': 'تسجيل الدخول',
    'header.accountAndLists': 'الحساب والقوائم',
    'header.alerts': 'التنبيهات',
    'header.cart': 'السلة',
    'header.todaysDeals': 'عروض اليوم',
    'header.customerService': 'خدمة العملاء',
    'header.registry': 'السجل',
    'header.giftCards': 'بطاقات الهدايا',
    'header.sell': 'بيع',
    'header.home': 'الرئيسية',
    'header.browseProducts': 'تصفح المنتجات',
    'header.signOut': 'تسجيل الخروج',
    'header.createAccount': 'إنشاء حساب',
    'header.departments': 'الأقسام',
    'header.adminDashboard': 'لوحة التحكم',
    'header.newCustomer': 'عميل جديد؟',
    'header.createNewAccount': 'إنشاء حساب جديد',
    'header.yourAccount': 'حسابك',
    'header.yourOrders': 'طلباتك',
    'header.yourLists': 'قوائمك',

    // Categories
    'category.pcs': 'أجهزة الكمبيوتر',
    'category.laptops': 'أجهزة اللابتوب',
    'category.mice': 'الفأرات',
    'category.keyboards': 'لوحات المفاتيح',
    'category.headphones': 'سماعات الرأس',
    'category.cables': 'الكابلات',
    'category.mousePads': 'وسائد الماوس',
    'category.hardDrives': 'الأقراص الصلبة',
    'category.books': 'الكتب',
    'category.fashion': 'الموضة',
    'category.homeKitchen': 'المنزل والمطبخ',

    // Auth
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.signInToAccount': 'تسجيل الدخول إلى حسابك',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.signingIn': 'جاري تسجيل الدخول...',
    'auth.newCustomer': 'عميل جديد؟',
    'auth.createAccount': 'إنشاء حساب',
    'auth.emailVerified': 'تم التحقق من البريد الإلكتروني! يمكنك الآن تسجيل الدخول.',
    'auth.createYourAccount': 'إنشاء حسابك',
    'auth.joinUs': 'انضم إلينا اليوم',
    'auth.name': 'الاسم',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.creatingAccount': 'جاري إنشاء الحساب...',
    'auth.alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'auth.signInHere': 'تسجيل الدخول هنا',

    // Home Page
    'home.shopByCategory': 'تسوق حسب الفئة',
    'home.viewAll': 'عرض الكل',
    'home.dealsOfTheDay': 'عروض اليوم',
    'home.seeAllDeals': 'عرض جميع العروض',
    'home.inspiredByHistory': 'مستوحى من سجل تصفحك',
    'home.trendingInElectronics': 'الأكثر رواجاً في الإلكترونيات',
    'home.signUpForBestExperience': 'سجل للحصول على أفضل تجربة',
    'home.signUp': 'سجل الآن',
    'home.pcAccessories': 'إكسسوارات الكمبيوتر والملحقات',
    'home.topRatedProducts': 'المنتجات الأعلى تقييماً',

    // Product
    'product.addToCart': 'أضف إلى السلة',
    'product.buyNow': 'اشتري الآن',
    'product.inStock': 'متوفر',
    'product.outOfStock': 'غير متوفر',
    'product.prime': 'برايم',
    'product.freeDelivery': 'توصيل مجاني',
    'product.quantity': 'الكمية',
    'product.reviews': 'تقييمات',
    'product.rating': 'تقييم',
    'product.price': 'السعر',
    'product.originalPrice': 'السعر الأصلي',
    'product.savings': 'وفرت',
    'product.description': 'الوصف',
    'product.specifications': 'المواصفات',
    'product.customerReviews': 'تقييمات العملاء',

    // Cart
    'cart.shoppingCart': 'سلة التسوق',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.items': 'منتجات',
    'cart.proceedToCheckout': 'متابعة الدفع',
    'cart.continueShopping': 'متابعة التسوق',
    'cart.remove': 'إزالة',
    'cart.price': 'السعر',
    'cart.qty': 'الكمية',

    // Checkout
    'checkout.secureCheckout': 'الدفع الآمن',
    'checkout.checkout': 'الدفع',
    'checkout.shippingAddress': 'عنوان الشحن',
    'checkout.paymentMethod': 'طريقة الدفع',
    'checkout.reviewOrder': 'مراجعة المنتجات والشحن',
    'checkout.fullName': 'الاسم الكامل',
    'checkout.address': 'العنوان',
    'checkout.city': 'المدينة',
    'checkout.state': 'المحافظة',
    'checkout.zipCode': 'الرمز البريدي',
    'checkout.phone': 'رقم الهاتف',
    'checkout.continueToPayment': 'متابعة للدفع',
    'checkout.change': 'تغيير',
    'checkout.creditCard': 'بطاقة ائتمان أو خصم',
    'checkout.paypal': 'باي بال',
    'checkout.giftCard': 'بطاقة هدايا',
    'checkout.cardNumber': 'رقم البطاقة',
    'checkout.nameOnCard': 'الاسم على البطاقة',
    'checkout.expirationDate': 'تاريخ الانتهاء',
    'checkout.securityCode': 'رمز الأمان',
    'checkout.continue': 'متابعة',
    'checkout.shippingSpeed': 'اختر سرعة الشحن:',
    'checkout.freeDelivery': 'توصيل مجاني',
    'checkout.standardDelivery': 'توصيل عادي',
    'checkout.expressDelivery': 'توصيل سريع',
    'checkout.arrives': 'يصل',
    'checkout.tomorrow': 'غداً',
    'checkout.itemsInOrder': 'المنتجات في طلبك:',
    'checkout.placeOrder': 'تأكيد الطلب',
    'checkout.orderSummary': 'ملخص الطلب',
    'checkout.shippingHandling': 'الشحن والتوصيل',
    'checkout.estimatedTax': 'الضريبة المقدرة',
    'checkout.orderTotal': 'إجمالي الطلب',
    'checkout.free': 'مجاني',
    'checkout.agreeTerms': 'بتأكيد طلبك، فإنك توافق على سياسة الخصوصية وشروط الاستخدام.',

    // Order Confirmation
    'confirmation.orderPlaced': 'تم تأكيد الطلب بنجاح!',
    'confirmation.thankYou': 'شكراً لطلبك!',
    'confirmation.emailConfirmation': 'ستتلقى تأكيداً بالبريد الإلكتروني قريباً.',
    'confirmation.orderDetails': 'تفاصيل الطلب',
    'confirmation.orderNumber': 'رقم الطلب',
    'confirmation.orderDate': 'تاريخ الطلب',
    'confirmation.estimatedDelivery': 'التوصيل المتوقع',
    'confirmation.viewOrders': 'عرض الطلبات',

    // Footer
    'footer.getToKnowUs': 'تعرف علينا',
    'footer.aboutUs': 'من نحن',
    'footer.careers': 'الوظائف',
    'footer.pressReleases': 'البيانات الصحفية',
    'footer.makeMoneyWithUs': 'اربح معنا',
    'footer.sellOnShop': 'بيع على المتجر',
    'footer.becomeAffiliate': 'كن شريكاً',
    'footer.advertiseProducts': 'أعلن عن منتجاتك',
    'footer.paymentProducts': 'منتجات الدفع',
    'footer.shopCard': 'بطاقة المتجر',
    'footer.currencyConverter': 'محول العملات',
    'footer.letUsHelpYou': 'دعنا نساعدك',
    'footer.returnsCenter': 'مركز الإرجاع',
    'footer.help': 'المساعدة',
    'footer.copyright': '© 2026 Shop.com، جميع الحقوق محفوظة',

    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.update': 'تحديث',
    'common.create': 'إنشاء',
    'common.edit': 'تعديل',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.apply': 'تطبيق',
    'common.clear': 'مسح',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.close': 'إغلاق',
    'common.submit': 'إرسال',
    'common.signInRequired': 'يرجى تسجيل الدخول لمتابعة الدفع',

    // Customer Service
    'customerService.title': 'خدمة العملاء',
    'customerService.howCanWeHelp': 'كيف يمكننا مساعدتك؟',

    // Gift Cards
    'giftCards.title': 'بطاقات الهدايا',
    'giftCards.subtitle': 'قدم الهدية المثالية',

    // Registry
    'registry.title': 'السجل',
    'registry.subtitle': 'إنشاء وإدارة سجلاتك',

    // Sell
    'sell.title': 'بيع على المتجر',
    'sell.subtitle': 'ابدأ ببيع منتجاتك اليوم',

    // Orders
    'orders.title': 'طلباتك',
    'orders.noOrders': 'لا توجد طلبات بعد',

    // Account
    'account.title': 'حسابك',
    'account.settings': 'إعدادات الحساب',

    // Lists
    'lists.title': 'قوائمك',
    'lists.noLists': 'لا توجد قوائم بعد',
    'lists.createList': 'إنشاء قائمة',

    // Admin Panel
    'admin.overview': 'نظرة عامة',
    'admin.categories': 'الفئات',
    'admin.products': 'المنتجات',
    'admin.suppliers': 'الموردين',
    'admin.customers': 'العملاء',
    'admin.orders': 'الطلبات',
    'admin.financial': 'الإدارة المالية',
    'admin.homeLayout': 'تخطيط الصفحة الرئيسية',
    'admin.files': 'الملفات',
    'admin.dashboard': 'لوحة التحكم',
    'admin.navMenu': 'قائمة التنقل',
    'admin.store': 'المتجر',
    'admin.exit': 'خروج',
    'admin.loading': 'جاري تحميل لوحة التحكم...',
    'admin.liveUpdate': 'التحديث فعال',
    
    // Admin Dashboard
    'admin.totalOrders': 'إجمالي الطلبات',
    'admin.totalRevenue': 'إجمالي الإيرادات',
    'admin.totalProducts': 'إجمالي المنتجات',
    'admin.totalCustomers': 'إجمالي العملاء',
    'admin.recentOrders': 'الطلبات الأخيرة',
    'admin.recentActivity': 'النشاط الأخير',
    'admin.salesOverview': 'نظرة عامة على المبيعات',
    'admin.viewAll': 'عرض الكل',
    'admin.newOrder': 'طلب جديد',
    'admin.noRecentOrders': 'لا توجد طلبات حديثة',
    'admin.noRecentActivity': 'لا يوجد نشاط حديث',
    
    // Admin Products
    'admin.addProduct': 'إضافة منتج',
    'admin.editProduct': 'تعديل المنتج',
    'admin.productName': 'اسم المنتج',
    'admin.productPrice': 'السعر',
    'admin.productStock': 'المخزون',
    'admin.productCategory': 'الفئة',
    'admin.productSupplier': 'المورد',
    'admin.productDescription': 'الوصف',
    'admin.productImage': 'صورة المنتج',
    'admin.originalPrice': 'السعر الأصلي',
    'admin.costPrice': 'سعر التكلفة',
    'admin.deleteProduct': 'حذف المنتج',
    'admin.confirmDelete': 'هل أنت متأكد من حذف هذا؟',
    
    // Admin Categories
    'admin.addCategory': 'إضافة فئة',
    'admin.editCategory': 'تعديل الفئة',
    'admin.categoryName': 'اسم الفئة',
    'admin.categoryImage': 'صورة الفئة',
    'admin.parentCategory': 'الفئة الأم',
    'admin.noParent': 'بدون أب (مستوى أعلى)',
    
    // Admin Orders
    'admin.orderId': 'رقم الطلب',
    'admin.customer': 'العميل',
    'admin.status': 'الحالة',
    'admin.date': 'التاريخ',
    'admin.amount': 'المبلغ',
    'admin.pending': 'قيد الانتظار',
    'admin.processing': 'قيد المعالجة',
    'admin.shipped': 'تم الشحن',
    'admin.delivered': 'تم التوصيل',
    'admin.cancelled': 'ملغي',
    'admin.orderDetails': 'تفاصيل الطلب',
    'admin.updateStatus': 'تحديث الحالة',
    
    // Admin Suppliers
    'admin.addSupplier': 'إضافة مورد',
    'admin.editSupplier': 'تعديل المورد',
    'admin.supplierName': 'اسم المورد',
    'admin.contactName': 'اسم جهة الاتصال',
    'admin.phone': 'الهاتف',
    'admin.addressLine': 'العنوان',
    
    // Admin Users/Customers
    'admin.userId': 'رقم المستخدم',
    'admin.userName': 'الاسم',
    'admin.userEmail': 'البريد الإلكتروني',
    'admin.role': 'الدور',
    'admin.joinedDate': 'تاريخ الانضمام',
    
    // Admin Financial
    'admin.revenue': 'الإيرادات',
    'admin.expenses': 'المصروفات',
    'admin.netProfit': 'صافي الربح',
    'admin.taxAmount': 'مبلغ الضريبة',
    'admin.currentCycle': 'الدورة الحالية',
    'admin.pastCycles': 'الدورات السابقة',
    'admin.addExpense': 'إضافة مصروف',
    'admin.closeCycle': 'إغلاق الدورة',
    
    // Admin Home Layout
    'admin.homeLayoutTitle': 'إعدادات تخطيط الصفحة الرئيسية',
    'admin.sectionEnabled': 'مفعل',
    'admin.sectionName': 'اسم القسم',
    'admin.showBadge': 'إظهار الشارة',
    'admin.badgeText': 'نص الشارة',
    'admin.manualSelection': 'اختيار يدوي',
    'admin.automaticSelection': 'اختيار تلقائي',
    'admin.selectProducts': 'اختر المنتجات',
    'admin.saveChanges': 'حفظ التغييرات',
    'admin.resetToDefault': 'إعادة للافتراضي',
    
    // Admin Files
    'admin.uploadFile': 'رفع ملف',
    'admin.fileName': 'اسم الملف',
    'admin.fileSize': 'الحجم',
    'admin.fileType': 'النوع',
    'admin.uploadDate': 'تاريخ الرفع',
    'admin.copyUrl': 'نسخ الرابط',
    'admin.deleteFile': 'حذف',
    
    // Common Admin
    'admin.actions': 'الإجراءات',
    'admin.noResults': 'لا توجد نتائج',
    'admin.searchPlaceholder': 'بحث...',
    'admin.itemsPerPage': 'عناصر في الصفحة',
    'admin.showing': 'عرض',
    'admin.of': 'من',
    'admin.save': 'حفظ',
    'admin.cancel': 'إلغاء',
    'admin.create': 'إنشاء',
    'admin.update': 'تحديث',
    'admin.delete': 'حذف',
    'admin.edit': 'تعديل',
    'admin.view': 'عرض',
    'admin.back': 'رجوع',
    
    // Admin Suppliers (extended)
    'admin.suppliersTitle': 'الموردين',
    'admin.suppliersSubtitle': 'إدارة موردي المنتجات والبائعين',
    'admin.totalSuppliers': 'إجمالي الموردين',
    'admin.searchSuppliers': 'البحث عن الموردين...',
    'admin.noSuppliersYet': 'لا يوجد موردين بعد',
    'admin.noSuppliersFound': 'لم يتم العثور على موردين',
    'admin.addFirstSupplier': 'أضف أول مورد للبدء',
    'admin.tryAdjustSearch': 'حاول تعديل البحث',
    'admin.createSupplier': 'إنشاء مورد',
    'admin.updateSupplier': 'تحديث المورد',
    'admin.supplierNameRequired': 'اسم المورد *',
    'admin.contactPerson': 'الشخص المسؤول',
    'admin.loadingSuppliers': 'جاري تحميل الموردين...',
    'admin.noContactInfo': 'لا توجد معلومات اتصال',
    
    // Admin Users (extended)
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.userManagementSubtitle': 'إدارة العملاء والمسؤولين',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.administrators': 'المسؤولين',
    'admin.searchUsers': 'البحث عن المستخدمين...',
    'admin.allUsers': 'كل المستخدمين',
    'admin.admins': 'المسؤولين',
    'admin.user': 'المستخدم',
    'admin.contact': 'الاتصال',
    'admin.location': 'الموقع',
    'admin.noUsersFound': 'لم يتم العثور على مستخدمين',
    'admin.tryAdjustFilters': 'حاول تعديل البحث أو معايير التصفية',
    'admin.editUserProfile': 'تعديل الملف الشخصي',
    'admin.fullName': 'الاسم الكامل',
    'admin.phoneNumber': 'رقم الهاتف',
    'admin.address': 'العنوان',
    'admin.userRole': 'دور المستخدم',
    'admin.administrator': 'مسؤول',
    'admin.loadingUsers': 'جاري تحميل المستخدمين...',
    'admin.unnamedUser': 'مستخدم بدون اسم',
    
    // Admin Financial (extended)
    'admin.financialManagement': 'الإدارة المالية',
    'admin.financialSubtitle': 'إدارة الدورات والمصروفات وتتبع الأرباح.',
    'admin.exportReport': 'تصدير التقرير',
    'admin.startNewCycle': 'بدء دورة جديدة',
    'admin.newExpense': 'مصروف جديد',
    'admin.activeCycle': 'دورة نشطة',
    'admin.noActiveCycle': 'لا توجد دورة نشطة',
    'admin.toPresent': 'حتى الآن',
    'admin.currentRevenue': 'الإيرادات الحالية',
    'admin.currentExpenses': 'المصروفات الحالية',
    'admin.estimatedTax': 'الضريبة المقدرة',
    'admin.payouts': 'المدفوعات',
    'admin.analysis': 'التحليل',
    'admin.recentTransactions': 'المعاملات الأخيرة',
    'admin.viewAllTransactions': 'عرض الكل',
    'admin.expenseLog': 'سجل المصروفات',
    'admin.expenseLogDesc': 'عرض تفصيلي لجميع المصروفات التشغيلية.',
    'admin.loadExpenseDashboard': 'تحميل لوحة المصروفات',
    'admin.supplierPayouts': 'مدفوعات الموردين',
    'admin.supplierPayoutsDesc': 'إدارة واعتماد المدفوعات للموردين.',
    'admin.viewPayoutStatus': 'عرض حالة المدفوعات',
    'admin.previousCycles': 'الدورات السابقة',
    'admin.profit': 'الربح',
    'admin.rev': 'الإيرادات',
    'admin.viewAllHistory': 'عرض كل السجل',
    'admin.cycleControls': 'التحكم بالدورات',
    'admin.closeCurrentCycle': 'إغلاق الدورة الحالية',
    'admin.financialProjection': 'التوقعات المالية',
    'admin.manageTaxSlabs': 'إدارة شرائح الضرائب',
    'admin.loadingFinancial': 'جاري تحميل السجلات المالية...',
    'admin.margin': 'الهامش',
    
    // Admin Categories Page
    'admin.availableCategories': 'الفئات المتاحة',
    'admin.totalCategories': 'إجمالي الفئات',
    'admin.withProducts': 'تحتوي منتجات',
    'admin.empty': 'فارغة',
    'admin.noDescription': 'لا يوجد وصف',
    'admin.noCategoriesFound': 'لم يتم العثور على فئات',
    'admin.tryAdjustingSearch': 'حاول تعديل كلمات البحث',
    'admin.getStartedCategories': 'ابدأ بإضافة فئتك الأولى',
    'admin.addFirstCategory': 'إضافة أول فئة',
    'admin.deleteCategory': 'حذف الفئة',
    'admin.deleteCategoryConfirm': 'هل أنت متأكد من حذف هذه الفئة؟ المنتجات في هذه الفئة ستصبح بدون فئة.',
    'admin.categoryNameRequired': 'الاسم *',
    'admin.nameInEnglish': 'الاسم بالإنجليزية',
    'admin.nameInArabic': 'الاسم بالعربية',
    'admin.selectCategory': 'اختر فئة...',
    'admin.optionalDescription': 'وصف اختياري',
    'admin.chooseFile': 'اختر ملف',
    'admin.takePhoto': 'التقط صورة',
    'admin.pasteImageUrl': 'أو الصق رابط الصورة:',
    
    // Admin Home Layout (extended)
    'admin.visibilityControl': 'التحكم في الظهور',
    'admin.visibilityControlDesc': 'استخدم المفاتيح أدناه لإخفاء أو إظهار أقسام معينة في صفحتك الرئيسية. هذا مفيد لإفساح المجال خلال فترات العروض أو إزالة الأقسام التي لا تحتوي على منتجات بعد.',
    'admin.countdownBadge': 'شارة العد التنازلي',
    'admin.manualProductSelection': 'اختيار المنتجات يدوياً',
    'admin.enabled': 'مفعل',
    'admin.disabled': 'معطل',
    'admin.manual': 'يدوي',
    'admin.automatic': 'تلقائي',
    'admin.selectProductsToFeature': 'اختر منتجات محددة لعرضها في هذا القسم.',
    'admin.selectProductsForBrowsing': 'اختر منتجات محددة لعرضها كتوصيات التصفح.',
    'admin.selectProductsForTrending': 'اختر منتجات محددة لعرضها كمنتجات رائجة.',
    'admin.selectProductsForAccessories': 'اختر منتجات محددة لعرضها كملحقات الكمبيوتر.',
    'admin.searchProducts': 'البحث عن المنتجات...',
    'admin.noProductsFound': 'لم يتم العثور على منتجات',
    'admin.autoShowsDiscounted': 'يعرض تلقائياً جميع المنتجات المخفضة (السعر الأصلي > السعر الحالي).',
    'admin.autoShowsFirst10': 'يعرض تلقائياً أول 10 منتجات كتوصيات.',
    'admin.autoShowsOver50': 'يعرض تلقائياً المنتجات بسعر أكثر من 50 جنيه.',
    'admin.autoShowsPeripherals': 'يعرض تلقائياً المنتجات التي تحتوي فئتها على ماوس أو كيبورد أو سماعات.',
    'admin.subtitleText': 'نص العنوان الفرعي',
    'admin.buttonText': 'نص الزر',
    'admin.visible': 'مرئي',
    'admin.hidden': 'مخفي',
    'admin.autoSyncingReady': 'المزامنة التلقائية جاهزة',
    'admin.realTimeUpdates': 'تحديثات فورية',
    'admin.versioning': 'الإصدار',
    'admin.sectionDescription': 'وصف القسم',
    'admin.enterBadgeText': 'أدخل نص الشارة (مثل: ينتهي في 12:34:56)',
    'admin.enterSubtitleText': 'أدخل نص العنوان الفرعي',
    'admin.enterButtonText': 'أدخل نص الزر',
};

const translations: Record<Language, Record<string, string>> = { en, ar };

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        return (saved === 'ar' || saved === 'en') ? saved : 'en';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    const formatCurrency = (amount: number): string => {
        const formattedNumber = amount.toLocaleString(language === 'ar' ? 'ar-EG' : 'en-EG');
        if (language === 'ar') {
            return `${formattedNumber} ج.م`;
        }
        return `E£${formattedNumber}`;
    };

    const isRTL = language === 'ar';

    // Apply RTL direction to document
    useEffect(() => {
        document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [isRTL, language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, formatCurrency }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
