import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    isRTL: boolean;
    formatCurrency: (amount: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// English translations
const en: Record<string, string> = {
    // Header
    'header.deliverTo': 'Deliver to',
    'header.location': 'Cairo & Giza',
    'header.searchPlaceholder': 'Search products...',
    'header.all': 'All',
    'header.hello': 'Hello',
    'header.signIn': 'sign in',
    'header.accountAndLists': 'Account & Lists',
    'header.alerts': 'Alerts',
    'header.cart': 'Cart',
    'header.todaysDeals': "Today's Deals",
    'header.customerService': 'Customer Service',
    'header.registry': 'Registry',
    'header.giftCards': 'Gift Cards',
    'header.sell': 'Sell',
    'header.home': 'Home',
    'header.browseProducts': 'Browse Products',
    'header.signOut': 'Sign Out',
    'header.createAccount': 'Create Account',
    'header.departments': 'Departments',
    'header.adminDashboard': 'Admin Dashboard',
    'header.newCustomer': 'New customer?',
    'header.createNewAccount': 'Create new account',
    'header.yourAccount': 'Your Account',
    'header.yourOrders': 'Your Orders',
    'header.yourLists': 'Your Lists',

    // Categories
    'category.pcs': 'PCs',
    'category.laptops': 'Laptops',
    'category.mice': 'Mice',
    'category.keyboards': 'Keyboards',
    'category.headphones': 'Headphones',
    'category.cables': 'Cables',
    'category.mousePads': 'Mouse Pads',
    'category.hardDrives': 'Hard Drives',
    'category.books': 'Books',
    'category.fashion': 'Fashion',
    'category.homeKitchen': 'Home & Kitchen',

    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInToAccount': 'Sign in to your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.signingIn': 'Signing in...',
    'auth.newCustomer': 'New customer?',
    'auth.createAccount': 'Create account',
    'auth.emailVerified': 'Email verified! You can now sign in.',
    'auth.createYourAccount': 'Create Your Account',
    'auth.joinUs': 'Join us today',
    'auth.name': 'Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.creatingAccount': 'Creating account...',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signInHere': 'Sign in here',

    // Home Page
    'home.shopByCategory': 'Shop by Category',
    'home.viewAll': 'View all',
    'home.dealsOfTheDay': 'Deals of the Day',
    'home.seeAllDeals': 'See all deals',
    'home.inspiredByHistory': 'Inspired by your browsing history',
    'home.trendingInElectronics': 'Trending in Electronics',
    'home.signUpForBestExperience': 'Sign up for the best experience',
    'home.signUp': 'Sign Up',
    'home.pcAccessories': 'PC Accessories & Peripherals',
    'home.topRatedProducts': 'Top Rated Products',
    'home.shopNow': 'Shop now',

    // Product
    'product.addToCart': 'Add to Cart',
    'product.buyNow': 'Buy Now',
    'product.inStock': 'In Stock',
    'product.outOfStock': 'Out of Stock',
    'product.prime': 'Prime',
    'product.freeDelivery': 'FREE Delivery',
    'product.tomorrow': 'Tomorrow',
    'product.quantity': 'Quantity',
    'product.reviews': 'reviews',
    'product.rating': 'rating',
    'product.price': 'Price',
    'product.originalPrice': 'Original Price',
    'product.savings': 'You Save',
    'product.description': 'Description',
    'product.specifications': 'Specifications',
    'product.customerReviews': 'Customer Reviews',

    // Cart
    'cart.shoppingCart': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.subtotal': 'Subtotal',
    'cart.items': 'items',
    'cart.proceedToCheckout': 'Proceed to Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.remove': 'Remove',
    'cart.price': 'Price',
    'cart.qty': 'Qty',

    // Checkout
    'checkout.secureCheckout': 'Secure Checkout',
    'checkout.checkout': 'Checkout',
    'checkout.shippingAddress': 'Shipping address',
    'checkout.paymentMethod': 'Payment method',
    'checkout.reviewOrder': 'Review items and shipping',
    'checkout.fullName': 'Full Name',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.state': 'State',
    'checkout.zipCode': 'ZIP Code',
    'checkout.phone': 'Phone Number',
    'checkout.continueToPayment': 'Continue to payment',
    'checkout.change': 'Change',
    'checkout.creditCard': 'Credit or debit card',
    'checkout.paypal': 'PayPal',
    'checkout.giftCard': 'Gift Card',
    'checkout.cardNumber': 'Card number',
    'checkout.nameOnCard': 'Name on card',
    'checkout.expirationDate': 'Expiration date',
    'checkout.securityCode': 'Security code',
    'checkout.continue': 'Continue',
    'checkout.shippingSpeed': 'Choose your shipping speed:',
    'checkout.freeDelivery': 'FREE Delivery',
    'checkout.standardDelivery': 'Standard Delivery',
    'checkout.expressDelivery': 'Express Delivery',
    'checkout.arrives': 'Arrives',
    'checkout.tomorrow': 'Tomorrow',
    'checkout.itemsInOrder': 'Items in your order:',
    'checkout.placeOrder': 'Place your order',
    'checkout.orderSummary': 'Order Summary',
    'checkout.shippingHandling': 'Shipping & handling',
    'checkout.estimatedTax': 'Estimated tax',
    'checkout.orderTotal': 'Order total',
    'checkout.free': 'FREE',
    'checkout.agreeTerms': 'By placing your order, you agree to our privacy notice and conditions of use.',

    // Order Confirmation
    'confirmation.orderPlaced': 'Order Placed Successfully!',
    'confirmation.thankYou': 'Thank you for your order!',
    'confirmation.emailConfirmation': 'You will receive an email confirmation shortly.',
    'confirmation.orderDetails': 'Order Details',
    'confirmation.orderNumber': 'Order Number',
    'confirmation.orderDate': 'Order Date',
    'confirmation.estimatedDelivery': 'Estimated Delivery',
    'confirmation.viewOrders': 'View Orders',

    // Footer
    'footer.getToKnowUs': 'Get to Know Us',
    'footer.aboutUs': 'About Us',
    'footer.careers': 'Careers',
    'footer.pressReleases': 'Press Releases',
    'footer.makeMoneyWithUs': 'Make Money with Us',
    'footer.sellOnShop': 'Sell on Shop',
    'footer.becomeAffiliate': 'Become an Affiliate',
    'footer.advertiseProducts': 'Advertise Your Products',
    'footer.paymentProducts': 'Payment Products',
    'footer.shopCard': 'Shop Card',
    'footer.currencyConverter': 'Shop Currency Converter',
    'footer.letUsHelpYou': 'Let Us Help You',
    'footer.returnsCenter': 'Returns Center',
    'footer.help': 'Help',
    'footer.copyright': '© 2026 Shop.com, Inc. or its affiliates',

    // About Us Page
    'aboutUs.title': 'About Us',
    'aboutUs.subtitle': 'Building the future of e-commerce in the Middle East',
    'aboutUs.ourMission': 'Our Mission',
    'aboutUs.missionText1': 'We are committed to providing the best online shopping experience by offering a wide selection of quality products at competitive prices with fast, reliable delivery.',
    'aboutUs.missionText2': 'We believe in putting our customers first and constantly innovating to meet their evolving needs in the digital age.',
    'aboutUs.ourValues': 'Our Values',
    'aboutUs.customerFirst': 'Customer First',
    'aboutUs.customerFirstDesc': 'Every decision we make starts with our customers in mind',
    'aboutUs.innovation': 'Innovation',
    'aboutUs.innovationDesc': 'Constantly improving and adopting new technologies',
    'aboutUs.trust': 'Trust & Integrity',
    'aboutUs.trustDesc': 'Building lasting relationships through honest practices',
    'aboutUs.sustainability': 'Sustainability',
    'aboutUs.sustainabilityDesc': 'Committed to environmentally responsible operations',
    'aboutUs.ourJourney': 'Our Journey',
    'aboutUs.milestone2015': 'Founded',
    'aboutUs.milestone2015Desc': 'Started as a small electronics store in Cairo',
    'aboutUs.milestone2017': 'Expansion',
    'aboutUs.milestone2017Desc': 'Expanded to cover all major cities in Egypt',
    'aboutUs.milestone2019': 'Mobile First',
    'aboutUs.milestone2019Desc': 'Launched our mobile app with 1M+ downloads',
    'aboutUs.milestone2021': 'Regional Growth',
    'aboutUs.milestone2021Desc': 'Expanded operations to Saudi Arabia and UAE',
    'aboutUs.milestone2023': '10M Customers',
    'aboutUs.milestone2023Desc': 'Reached 10 million active customers milestone',
    'aboutUs.milestone2025': 'AI Integration',
    'aboutUs.milestone2025Desc': 'Introduced AI-powered shopping recommendations',
    'aboutUs.leadershipTeam': 'Leadership Team',
    'aboutUs.roleCEO': 'Chief Executive Officer',
    'aboutUs.roleCTO': 'Chief Technology Officer',
    'aboutUs.roleCOO': 'Chief Operations Officer',
    'aboutUs.roleCMO': 'Chief Marketing Officer',
    'aboutUs.awardsTitle': 'Awards & Recognition',
    'aboutUs.award1': 'Best E-Commerce Platform',
    'aboutUs.award2': 'Customer Excellence Award',
    'aboutUs.award3': 'Innovation in Retail',
    'aboutUs.statCustomers': 'Active Customers',
    'aboutUs.statCountries': 'Countries Served',
    'aboutUs.statProducts': 'Products Available',
    'aboutUs.statSupport': 'Customer Support',

    // Careers Page
    'careers.title': 'Join Our Team',
    'careers.subtitle': 'Build your career at one of the fastest-growing e-commerce companies',
    'careers.searchPlaceholder': 'Search job openings...',
    'careers.whyJoinUs': 'Why Join Us',
    'careers.benefitHealth': 'Health & Wellness',
    'careers.benefitHealthDesc': 'Comprehensive health insurance for you and your family',
    'careers.benefitLearning': 'Learning & Development',
    'careers.benefitLearningDesc': 'Annual education budget and access to online courses',
    'careers.benefitBalance': 'Work-Life Balance',
    'careers.benefitBalanceDesc': 'Flexible hours and remote work options',
    'careers.benefitGrowth': 'Career Growth',
    'careers.benefitGrowthDesc': 'Clear paths for advancement and mentorship programs',
    'careers.lifeAtShop': 'Life at Shop.com',
    'careers.lifeAtShopText1': 'We are a diverse team of passionate individuals working together to transform e-commerce in the region.',
    'careers.lifeAtShopText2': 'Our culture celebrates innovation, collaboration, and personal growth. We believe happy employees create happy customers.',
    'careers.openPositions': 'Open Positions',
    'careers.allDepartments': 'All Departments',
    'careers.engineering': 'Engineering',
    'careers.product': 'Product',
    'careers.marketing': 'Marketing',
    'careers.operations': 'Operations',
    'careers.customerService': 'Customer Service',
    'careers.noJobsFound': 'No jobs found matching your criteria',
    'careers.applyNow': 'Apply Now',
    'careers.dontSeeRole': 'Don\'t see your role?',
    'careers.dontSeeRoleText': 'We\'re always looking for talented people. Send us your resume and we\'ll keep you in mind for future opportunities.',
    'careers.sendResume': 'Send Your Resume',

    // Press Releases Page
    'press.title': 'Press Releases',
    'press.subtitle': 'Latest news and announcements from Shop.com',
    'press.featured': 'Featured',
    'press.latestNews': 'Latest News',
    'press.filterByYear': 'Filter by Year',
    'press.newsFrom': 'News from',
    'press.releases': 'releases',
    'press.noReleases': 'No press releases found for this year',
    'press.readMore': 'Read More',
    'press.mediaContacts': 'Media Contacts',
    'press.mediaKit': 'Media Kit',
    'press.mediaKitDesc': 'Download our brand assets, logos, and fact sheet for press coverage.',
    'press.downloadKit': 'Download Media Kit',
    'press.release1Title': 'Shop.com Announces Record-Breaking Holiday Sales',
    'press.release1Summary': 'E-commerce platform reports 150% increase in sales compared to previous year during holiday season.',
    'press.release2Title': 'New Same-Day Delivery Service Launched in Cairo',
    'press.release2Summary': 'Customers in Cairo can now receive orders within hours with our new express delivery option.',
    'press.release3Title': 'Shop.com Partners with Leading Electronics Brands',
    'press.release3Summary': 'Strategic partnerships bring exclusive products and better prices to our customers.',
    'press.release4Title': 'Mobile App Reaches 5 Million Downloads',
    'press.release4Summary': 'Our shopping app continues to grow with enhanced features and better user experience.',
    'press.release5Title': 'Shop.com Wins Best E-Commerce Platform Award',
    'press.release5Summary': 'Recognized for innovation and customer service excellence at the MENA Tech Awards.',
    'press.release6Title': 'Expansion of Warehouse Network',
    'press.release6Summary': 'New fulfillment centers opened in Alexandria and Aswan for faster regional delivery.',
    'press.release7Title': 'Launch of Shop.com Credit Card',
    'press.release7Summary': 'New co-branded card offers exclusive cashback and financing options for customers.',
    'press.release8Title': 'Shop.com Celebrates 1 Million Active Sellers',
    'press.release8Summary': 'Marketplace milestone reflects growing trust in our seller ecosystem.',

    // Affiliate Page
    'affiliate.title': 'Affiliate Program',
    'affiliate.subtitle': 'Earn commissions by sharing products you love with your audience',
    'affiliate.joinNow': 'Join Now',
    'affiliate.learnMore': 'Learn More',
    'affiliate.earnWhileYouShare': 'Earn While You Share',
    'affiliate.earnWhileYouShareDesc': 'Turn your content into income by recommending products to your followers',
    'affiliate.whyJoin': 'Why Join Our Program?',
    'affiliate.earnCommissions': 'Earn Commissions',
    'affiliate.earnCommissionsDesc': 'Get up to 12% on qualifying purchases',
    'affiliate.trackPerformance': 'Track Performance',
    'affiliate.trackPerformanceDesc': 'Real-time dashboard to monitor clicks and earnings',
    'affiliate.easySharing': 'Easy Sharing',
    'affiliate.easySharingDesc': 'Create links, banners, and widgets in seconds',
    'affiliate.dedicatedSupport': 'Dedicated Support',
    'affiliate.dedicatedSupportDesc': 'Expert team to help you maximize earnings',
    'affiliate.commissionRates': 'Commission Rates',
    'affiliate.tierElectronics': 'Electronics',
    'affiliate.tierFashion': 'Fashion',
    'affiliate.tierHome': 'Home & Kitchen',
    'affiliate.tierBooks': 'Books',
    'affiliate.tierBeauty': 'Beauty',
    'affiliate.tierSports': 'Sports',
    'affiliate.ratesDisclaimer': 'Commission rates may vary by category and promotional periods',
    'affiliate.howItWorks': 'How It Works',
    'affiliate.step1Title': 'Sign Up Free',
    'affiliate.step1Desc': 'Create your affiliate account in minutes',
    'affiliate.step2Title': 'Share Products',
    'affiliate.step2Desc': 'Create unique links for products you love',
    'affiliate.step3Title': 'Earn Money',
    'affiliate.step3Desc': 'Get paid for every qualifying purchase',
    'affiliate.step4Title': 'Get Paid',
    'affiliate.step4Desc': 'Receive payments monthly via bank transfer',
    'affiliate.startEarning': 'Ready to Start Earning?',
    'affiliate.joinFree': 'Join our affiliate program for free today',
    'affiliate.firstName': 'First Name',
    'affiliate.lastName': 'Last Name',
    'affiliate.email': 'Email Address',
    'affiliate.website': 'Website or Social Media',
    'affiliate.audience': 'Audience Size',
    'affiliate.selectAudience': 'Select your audience size',
    'affiliate.createAccount': 'Create Affiliate Account',
    'affiliate.termsAgreement': 'By signing up, you agree to our Affiliate Terms and Conditions',
    'affiliate.faq': 'Frequently Asked Questions',
    'affiliate.faq1': 'How do I get paid?',
    'affiliate.faq1Answer': 'Payments are made monthly via bank transfer once you reach the minimum threshold of E£100.',
    'affiliate.faq2': 'How long do cookies last?',
    'affiliate.faq2Answer': 'Our cookies last 30 days, so you earn commissions on purchases made within that window.',
    'affiliate.faq3': 'Can I promote on social media?',
    'affiliate.faq3Answer': 'Yes! You can share affiliate links on blogs, YouTube, Instagram, TikTok, and other platforms.',
    'affiliate.faq4': 'Is there a minimum audience requirement?',
    'affiliate.faq4Answer': 'No minimum required, but larger audiences typically earn more commissions.',
    'affiliate.statPaid': 'Paid to Affiliates',
    'affiliate.statAffiliates': 'Active Affiliates',
    'affiliate.statAvgCommission': 'Avg. Commission',
    'affiliate.statCookieDays': 'Cookie Duration (Days)',

    // Advertise Page
    'advertise.title': 'Advertise Your Products',
    'advertise.subtitle': 'Reach millions of shoppers actively looking to buy',
    'advertise.getStarted': 'Get Started',
    'advertise.contactSales': 'Contact Sales',
    'advertise.reachYourCustomers': 'Reach Your Customers',
    'advertise.reachYourCustomersDesc': 'Target shoppers based on their interests, search history, and buying behavior',
    'advertise.adSolutions': 'Advertising Solutions',
    'advertise.sponsoredProducts': 'Sponsored Products',
    'advertise.sponsoredProductsDesc': 'Promote individual listings in search results and product pages',
    'advertise.sponsoredBrands': 'Sponsored Brands',
    'advertise.sponsoredBrandsDesc': 'Showcase your brand with custom headlines and multiple products',
    'advertise.displayAds': 'Display Ads',
    'advertise.displayAdsDesc': 'Reach customers across our website with visual banner ads',
    'advertise.featurePayPerClick': 'Pay-per-click pricing',
    'advertise.featureKeywordTargeting': 'Keyword targeting',
    'advertise.featureAutoOptimization': 'Auto campaign optimization',
    'advertise.featureCustomHeadline': 'Custom headline',
    'advertise.featureBrandLogo': 'Brand logo display',
    'advertise.featureMultipleProducts': 'Feature multiple products',
    'advertise.featureAudienceTargeting': 'Audience targeting',
    'advertise.featureRetargeting': 'Retargeting capabilities',
    'advertise.featureRichMedia': 'Rich media support',
    'advertise.learnMore': 'Learn More',
    'advertise.howItWorks': 'How It Works',
    'advertise.step1Title': 'Create Campaign',
    'advertise.step1Desc': 'Set up your campaign and choose products to promote',
    'advertise.step2Title': 'Set Budget',
    'advertise.step2Desc': 'Define daily or total campaign budget',
    'advertise.step3Title': 'Target Audience',
    'advertise.step3Desc': 'Select keywords, demographics, and interests',
    'advertise.step4Title': 'Launch & Optimize',
    'advertise.step4Desc': 'Go live and monitor performance in real-time',
    'advertise.successStories': 'Success Stories',
    'advertise.testimonial1': 'Sponsored Products helped us reach new customers and increase sales by 250% in just 3 months.',
    'advertise.testimonial2': 'The targeting options are incredible. We\'ve seen a massive increase in brand awareness.',
    'advertise.testimonial3': 'Display ads drove significant traffic to our store, with great conversion rates.',
    'advertise.startAdvertising': 'Start Advertising Today',
    'advertise.contactUsToday': 'Fill out the form and our team will contact you within 24 hours',
    'advertise.companyName': 'Company Name',
    'advertise.contactName': 'Contact Name',
    'advertise.email': 'Email',
    'advertise.phone': 'Phone',
    'advertise.monthlyBudget': 'Monthly Advertising Budget',
    'advertise.selectBudget': 'Select your budget range',
    'advertise.message': 'Message',
    'advertise.messagePlaceholder': 'Tell us about your advertising goals...',
    'advertise.submitInquiry': 'Submit Inquiry',
    'advertise.statActiveShoppers': 'Active Shoppers',
    'advertise.statAvgROI': 'Average ROI',
    'advertise.statMinCPC': 'Min. Cost Per Click',
    'advertise.statCampaignApproval': 'Campaign Approval',

    // Shop Card Page
    'shopCard.title': 'Shop Card',
    'shopCard.subtitle': 'The smart way to shop - earn cashback on every purchase',
    'shopCard.applyNow': 'Apply Now',
    'shopCard.learnMore': 'Learn More',
    'shopCard.cardHolder': 'CARD HOLDER',
    'shopCard.cardBenefits': 'Card Benefits',
    'shopCard.cashback': 'Up to 7% Cashback',
    'shopCard.cashbackDesc': 'Earn cashback on every purchase at Shop.com',
    'shopCard.welcomeBonus': 'Welcome Bonus',
    'shopCard.welcomeBonusDesc': 'Get E£500 bonus on your first purchase',
    'shopCard.nannualFee': 'No Annual Fee',
    'shopCard.noAnnualFeeDesc': 'Zero fees - no hidden charges ever',
    'shopCard.secureShopping': 'Secure Shopping',
    'shopCard.secureShoppingDesc': 'Protected by advanced fraud prevention',
    'shopCard.cashbackTiers': 'Cashback Tiers',
    'shopCard.tierBasic': 'Basic',
    'shopCard.tierSilver': 'Silver',
    'shopCard.tierGold': 'Gold',
    'shopCard.tierPlatinum': 'Platinum',
    'shopCard.cashbackLabel': 'Cashback',
    'shopCard.minSpend': 'Min. Annual Spend',
    'shopCard.allFeatures': 'All Card Features',
    'shopCard.feature1': 'Instant approval and digital card',
    'shopCard.feature2': 'Exclusive member-only deals',
    'shopCard.feature3': 'Free express shipping on orders over E£500',
    'shopCard.feature4': 'Extended warranty on electronics',
    'shopCard.feature5': 'Priority customer support',
    'shopCard.feature6': 'Easy installment options up to 24 months',
    'shopCard.rewardsBalance': 'Your Rewards Balance',
    'shopCard.rewardsBalanceDesc': 'Rewards can be redeemed for purchases or transferred to your bank',
    'shopCard.redeemRewards': 'Redeem Rewards',
    'shopCard.applyForCard': 'Apply for Shop Card',
    'shopCard.quickApproval': 'Get approved in minutes - no paperwork required',
    'shopCard.fullName': 'Full Name',
    'shopCard.email': 'Email Address',
    'shopCard.phone': 'Phone Number',
    'shopCard.nationalId': 'National ID Number',
    'shopCard.monthlyIncome': 'Monthly Income',
    'shopCard.selectIncome': 'Select your income range',
    'shopCard.agreeTerms': 'I agree to the Terms & Conditions and Privacy Policy',
    'shopCard.submitApplication': 'Submit Application',
    'shopCard.secureApplication': 'Your information is secure and encrypted',
    'shopCard.faq': 'Frequently Asked Questions',
    'shopCard.faq1': 'How do I earn cashback?',
    'shopCard.faq1Answer': 'Cashback is automatically credited to your account after each purchase. Higher tiers earn more cashback.',
    'shopCard.faq2': 'Can I use the card outside of Shop.com?',
    'shopCard.faq2Answer': 'The Shop Card is exclusively for purchases on Shop.com. For external purchases, you earn 1% cashback.',
    'shopCard.faq3': 'How long does approval take?',
    'shopCard.faq3Answer': 'Most applications are approved within minutes. You\'ll receive your digital card immediately upon approval.',

    // Currency Converter Page
    'currency.title': 'Currency Converter',
    'currency.subtitle': 'Convert currencies and see prices in your preferred currency',
    'currency.convertNow': 'Convert Currency',
    'currency.amount': 'Amount',
    'currency.from': 'From',
    'currency.to': 'To',
    'currency.rateDisclaimer': 'Rates are for reference only and may differ from actual transaction rates',
    'currency.popularRates': 'Popular Exchange Rates',
    'currency.whyUseOurs': 'Why Use Our Converter?',
    'currency.featureRealTime': 'Real-Time Rates',
    'currency.featureRealTimeDesc': 'Exchange rates updated every minute',
    'currency.featureSecure': 'Secure & Reliable',
    'currency.featureSecureDesc': 'Trusted by millions of users',
    'currency.featureGlobal': 'Global Coverage',
    'currency.featureGlobalDesc': '150+ currencies supported',
    'currency.featureFast': 'Fast & Easy',
    'currency.featureFastDesc': 'Convert in seconds',
    'currency.howToUse': 'How to Use at Checkout',
    'currency.step1Title': 'Select Currency',
    'currency.step1Desc': 'Choose your preferred currency in your account settings',
    'currency.step2Title': 'Shop Normally',
    'currency.step2Desc': 'Browse and add items to your cart as usual',
    'currency.step3Title': 'Pay in Your Currency',
    'currency.step3Desc': 'See prices and pay in your selected currency at checkout',
    'currency.noHiddenFees': 'No Hidden Conversion Fees',
    'currency.noHiddenFeesDesc': 'The price you see is the price you pay - no surprise charges',
    'currency.egyptianPound': 'Egyptian Pound',
    'currency.usDollar': 'US Dollar',
    'currency.euro': 'Euro',
    'currency.britishPound': 'British Pound',
    'currency.saudiRiyal': 'Saudi Riyal',
    'currency.uaeDirham': 'UAE Dirham',
    'currency.kuwaitiDinar': 'Kuwaiti Dinar',
    'currency.qatariRiyal': 'Qatari Riyal',
    'currency.bahrainiDinar': 'Bahraini Dinar',
    'currency.omaniRial': 'Omani Rial',
    'currency.jordanianDinar': 'Jordanian Dinar',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.apply': 'Apply',
    'common.clear': 'Clear',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.signInRequired': 'Please sign in to continue checkout',

    // Customer Service
    'customerService.title': 'Customer Service',
    'customerService.howCanWeHelp': 'How can we help you?',
    'customerService.searchHelp': 'Search our help library or browse by category',
    'customerService.searchPlaceholder': 'Describe your issue...',
    'customerService.quickLinks': 'Quick Links',
    'customerService.trackPackage': 'Track Package',
    'customerService.trackPackageDesc': 'Check the status of your orders',
    'customerService.returnsRefunds': 'Returns & Refunds',
    'customerService.returnsRefundsDesc': 'Return or exchange items',
    'customerService.paymentSettings': 'Payment Settings',
    'customerService.paymentSettingsDesc': 'Manage payment methods',
    'customerService.accountSecurity': 'Account Security',
    'customerService.accountSecurityDesc': 'Update password and settings',
    'customerService.deliveryIssues': 'Delivery Issues',
    'customerService.deliveryIssuesDesc': 'Report delivery problems',
    'customerService.contactUs': 'Contact Us',
    'customerService.contactUsDesc': 'Chat with customer support',
    'customerService.browseByTopic': 'Browse by Topic',
    'customerService.ordersShipping': 'Orders & Shipping',
    'customerService.ordersShippingQ1': 'How do I track my order?',
    'customerService.ordersShippingQ2': 'What are the shipping options?',
    'customerService.ordersShippingQ3': 'Can I change my shipping address?',
    'customerService.ordersShippingQ4': 'How long does delivery take?',
    'customerService.returnsRefundsSection': 'Returns & Refunds',
    'customerService.returnsRefundsQ1': 'How do I return an item?',
    'customerService.returnsRefundsQ2': 'What is your return policy?',
    'customerService.returnsRefundsQ3': 'When will I get my refund?',
    'customerService.returnsRefundsQ4': 'Can I exchange an item?',
    'customerService.accountSecuritySection': 'Account & Security',
    'customerService.accountSecurityQ1': 'How do I reset my password?',
    'customerService.accountSecurityQ2': 'How do I update my email?',
    'customerService.accountSecurityQ3': 'Is my payment information secure?',
    'customerService.accountSecurityQ4': 'How do I delete my account?',
    'customerService.paymentPricing': 'Payment & Pricing',
    'customerService.paymentPricingQ1': 'What payment methods do you accept?',
    'customerService.paymentPricingQ2': 'Why was I charged sales tax?',
    'customerService.paymentPricingQ3': 'Do you offer price matching?',
    'customerService.paymentPricingQ4': 'How do I use a gift card?',
    'customerService.stillNeedHelp': 'Still Need Help?',
    'customerService.liveChat': 'Live Chat',
    'customerService.liveChatDesc': 'Chat with our support team',
    'customerService.startChat': 'Start Chat',
    'customerService.phoneSupport': 'Phone Support',
    'customerService.phoneSupportDesc': 'Call us: 1-800-123-4567',
    'customerService.requestCallback': 'Request Callback',
    'customerService.emailSupport': 'Email Support',
    'customerService.emailSupportDesc': 'Get help via email',
    'customerService.sendEmail': 'Send Email',
    'customerService.lookingForOrders': 'Looking for your orders?',
    'customerService.lookingForOrdersDesc': 'View order status, tracking information, and more',
    'customerService.viewOrders': 'View Orders',

    // Gift Cards
    'giftCards.title': 'Gift Cards',
    'giftCards.subtitle': 'The perfect gift for any occasion. Choose from millions of items.',
    'giftCards.createYourGiftCard': 'Create Your Gift Card',
    'giftCards.design': '1. Design',
    'giftCards.amount': '2. Amount',
    'giftCards.delivery': '3. Delivery',
    'giftCards.chooseDesign': 'Choose a Design',
    'giftCards.birthdayCelebration': 'Birthday Celebration',
    'giftCards.birthday': 'Birthday',
    'giftCards.thankYou': 'Thank You',
    'giftCards.congratulations': 'Congratulations',
    'giftCards.celebration': 'Celebration',
    'giftCards.holidaySpecial': 'Holiday Special',
    'giftCards.holiday': 'Holiday',
    'giftCards.classicBlue': 'Classic Blue',
    'giftCards.classic': 'Classic',
    'giftCards.weddingGift': 'Wedding Gift',
    'giftCards.wedding': 'Wedding',
    'giftCards.selectAmount': 'Select Amount',
    'giftCards.enterCustomAmount': 'Or enter a custom amount',
    'giftCards.minMaxAmount': 'Minimum: E£1.00 | Maximum: E£2,000.00',
    'giftCards.deliveryMethod': 'Delivery Method',
    'giftCards.email': 'Email',
    'giftCards.instantDelivery': 'Instant delivery',
    'giftCards.textMessage': 'Text Message',
    'giftCards.deliveredInMinutes': 'Delivered in minutes',
    'giftCards.physicalCard': 'Physical Card',
    'giftCards.shipsInDays': 'Ships in 3-5 business days (+ E£5.99)',
    'giftCards.recipientEmail': 'Recipient Email',
    'giftCards.yourName': 'Your Name',
    'giftCards.personalMessage': 'Personal Message (Optional)',
    'giftCards.addPersonalMessage': 'Add a personal message...',
    'giftCards.deliveryDate': 'Delivery Date',
    'giftCards.orderSummary': 'Order Summary',
    'giftCards.giftCard': 'Gift Card',
    'giftCards.cardValue': 'Card Value:',
    'giftCards.deliveryLabel': 'Delivery:',
    'giftCards.free': 'FREE',
    'giftCards.total': 'Total:',
    'giftCards.addToCart': 'Add to Cart',
    'giftCards.continueShopping': 'Continue Shopping',
    'giftCards.whyChoose': 'Why Choose Our Gift Cards?',
    'giftCards.instantDeliveryTitle': 'Instant Delivery',
    'giftCards.instantDeliveryDesc': 'Email gift cards are delivered within minutes',
    'giftCards.noFees': 'No Fees',
    'giftCards.noFeesDesc': 'No purchase or inactivity fees',
    'giftCards.neverExpires': 'Never Expires',
    'giftCards.neverExpiresDesc': 'Our gift cards never expire',
    'giftCards.perfectGift': 'Perfect Gift',
    'giftCards.perfectGiftDesc': 'Let them choose what they want',
    'giftCards.faq': 'Frequently Asked Questions',
    'giftCards.faq1': 'How do I check my gift card balance?',
    'giftCards.faq1Answer': 'You can check your gift card balance by logging into your account and viewing the "Gift Card Balance" section.',
    'giftCards.faq2': 'Can I use multiple gift cards on one order?',
    'giftCards.faq2Answer': 'Yes, you can apply multiple gift cards to a single order during checkout.',
    'giftCards.faq3': 'Do gift cards expire?',
    'giftCards.faq3Answer': 'No, our gift cards never expire and have no fees.',
    'giftCards.faq4': 'Can I reload my gift card?',
    'giftCards.faq4Answer': 'Yes, you can reload your gift card with any amount from E£1 to E£2,000.',

    // Registry
    'registry.title': 'Gift Registry',
    'registry.subtitle': 'Create your perfect registry and share it with loved ones',
    'registry.createRegistry': 'Create a Registry',
    'registry.findRegistry': 'Find a Registry',
    'registry.chooseType': 'Choose Your Registry Type',
    'registry.weddingRegistry': 'Wedding Registry',
    'registry.weddingRegistryDesc': 'Start your new life together with gifts you\'ll love',
    'registry.babyRegistry': 'Baby Registry',
    'registry.babyRegistryDesc': 'Get ready for your little one with everything you need',
    'registry.birthdayGraduation': 'Birthday & Graduation',
    'registry.birthdayGraduationDesc': 'Celebrate milestones with the perfect gifts',
    'registry.housewarming': 'Housewarming',
    'registry.housewarmingDesc': 'Make your new house feel like home',
    'registry.getStarted': 'Get Started',
    'registry.firstName': 'First Name',
    'registry.lastName': 'Last Name',
    'registry.eventDate': 'Event Date (Optional)',
    'registry.searchRegistries': 'Search Registries',
    'registry.popularItems': 'Most Popular Registry Items',
    'registry.onRegistries': 'On {count} registries',
    'registry.whyCreate': 'Why Create a Registry?',
    'registry.easyToCreate': 'Easy to Create',
    'registry.easyToCreateDesc': 'Set up your registry in minutes',
    'registry.easyToShare': 'Easy to Share',
    'registry.easyToShareDesc': 'Share with family and friends instantly',
    'registry.groupGifting': 'Group Gifting',
    'registry.groupGiftingDesc': 'Let multiple people contribute to big items',
    'registry.freeReturns': 'Free Returns',
    'registry.freeReturnsDesc': '90-day return policy on registry items',
    'registry.readyToCreate': 'Ready to Create Your Registry?',
    'registry.readyToCreateDesc': 'It only takes a few minutes to set up. Add items from millions of products and share with friends and family.',
    'registry.browseProducts': 'Browse Products',

    // Sell
    'sell.title': 'Start Selling Today',
    'sell.subtitle': 'Join millions of sellers and grow your business with our powerful e-commerce platform',
    'sell.startSelling': 'Start Selling',
    'sell.learnMore': 'Learn More',
    'sell.yourStoreYourSuccess': 'Your Store, Your Success',
    'sell.yourStoreDesc': 'Everything you need to build and manage a successful online business',
    'sell.statActiveBuyers': 'Active Buyers',
    'sell.statSellersWorldwide': 'Sellers Worldwide',
    'sell.statProductsListed': 'Products Listed',
    'sell.statCustomerSatisfaction': 'Customer Satisfaction',
    'sell.whySellWithUs': 'Why Sell With Us?',
    'sell.millionsOfCustomers': 'Millions of Customers',
    'sell.millionsOfCustomersDesc': 'Reach millions of active shoppers looking for products like yours',
    'sell.growYourBusiness': 'Grow Your Business',
    'sell.growYourBusinessDesc': 'Tools and insights to help scale your business',
    'sell.easyFulfillment': 'Easy Fulfillment',
    'sell.easyFulfillmentDesc': 'We can handle storage, packing, and shipping for you',
    'sell.sellerSupport': 'Seller Support',
    'sell.sellerSupportDesc': 'Dedicated support team to help you succeed',
    'sell.choosePlan': 'Choose Your Selling Plan',
    'sell.individual': 'Individual',
    'sell.professional': 'Professional',
    'sell.perItemSold': 'per item sold',
    'sell.perMonth': 'per month',
    'sell.recommended': 'Recommended',
    'sell.individualFeature1': 'No monthly subscription fee',
    'sell.individualFeature2': 'Pay only when you sell',
    'sell.individualFeature3': 'Access to basic selling tools',
    'sell.individualFeature4': 'Sell up to 40 items per month',
    'sell.professionalFeature1': 'No per-item fees',
    'sell.professionalFeature2': 'Unlimited listings',
    'sell.professionalFeature3': 'Advanced selling tools',
    'sell.professionalFeature4': 'Bulk listing and reporting',
    'sell.professionalFeature5': 'API access',
    'sell.professionalFeature6': 'Featured placement options',
    'sell.howItWorks': 'How It Works',
    'sell.step1Title': 'Create Your Account',
    'sell.step1Desc': 'Sign up and provide your business information',
    'sell.step2Title': 'List Your Products',
    'sell.step2Desc': 'Add product details, images, and pricing',
    'sell.step3Title': 'Start Selling',
    'sell.step3Desc': 'Receive orders and manage your inventory',
    'sell.step4Title': 'Get Paid',
    'sell.step4Desc': 'Receive payments directly to your bank account',
    'sell.readyToStart': 'Ready to Start Selling?',
    'sell.createInMinutes': 'Create your seller account in minutes',
    'sell.businessName': 'Business Name',
    'sell.emailAddress': 'Email Address',
    'sell.phoneNumber': 'Phone Number',
    'sell.productCategory': 'Product Category',
    'sell.selectCategory': 'Select a category',
    'sell.electronics': 'Electronics',
    'sell.fashion': 'Fashion',
    'sell.homeKitchen': 'Home & Kitchen',
    'sell.books': 'Books',
    'sell.sportsOutdoors': 'Sports & Outdoors',
    'sell.other': 'Other',
    'sell.createSellerAccount': 'Create Seller Account',
    'sell.termsAgreement': 'By creating an account, you agree to our Terms of Service and Privacy Policy',
    'sell.successStories': 'Seller Success Stories',
    'sell.story1Name': 'Sarah\'s Boutique',
    'sell.story1Quote': 'I went from selling locally to reaching customers nationwide. My sales have tripled!',
    'sell.story1Revenue': 'E£50K+ monthly',
    'sell.story2Name': 'Tech Gadgets Pro',
    'sell.story2Quote': 'The fulfillment service saved me so much time. I can focus on growing my product line.',
    'sell.story2Revenue': 'E£100K+ monthly',
    'sell.story3Name': 'HomeStyle Decor',
    'sell.story3Quote': 'Starting was so easy. Within a week, I made my first sale. Now it\'s my full-time business!',
    'sell.story3Revenue': 'E£30K+ monthly',

    // Orders
    'orders.title': 'Your Orders',
    'orders.noOrders': 'You have no orders yet',

    // Account
    'account.title': 'Your Account',
    'account.settings': 'Account Settings',

    // Lists
    'lists.title': 'Your Lists',
    'lists.noLists': 'You have no lists yet',
    'lists.createList': 'Create a List',

    // Admin Panel
    'admin.overview': 'Admin Overview',
    'admin.categories': 'Categories',
    'admin.products': 'Products',
    'admin.suppliers': 'Suppliers',
    'admin.customers': 'Customers',
    'admin.orders': 'Orders',
    'admin.financial': 'Management Financial',
    'admin.homeLayout': 'Home Layout',
    'admin.files': 'Files',
    'admin.dashboard': 'Dashboard',
    'admin.navMenu': 'Navigation Menu',
    'admin.store': 'Store',
    'admin.exit': 'Exit',
    'admin.loading': 'Loading admin panel...',
    'admin.liveUpdate': 'Live Update Applied',
    
    // Admin Dashboard
    'admin.totalOrders': 'Total Orders',
    'admin.totalRevenue': 'Total Revenue',
    'admin.totalProducts': 'Total Products',
    'admin.totalCustomers': 'Total Customers',
    'admin.recentOrders': 'Recent Orders',
    'admin.recentActivity': 'Recent Activity',
    'admin.salesOverview': 'Sales Overview',
    'admin.viewAll': 'View All',
    'admin.newOrder': 'New order',
    'admin.noRecentOrders': 'No recent orders',
    'admin.noRecentActivity': 'No recent activity',
    
    // Admin Products
    'admin.addProduct': 'Add Product',
    'admin.editProduct': 'Edit Product',
    'admin.productName': 'Product Name',
    'admin.productPrice': 'Price',
    'admin.productStock': 'Stock',
    'admin.productCategory': 'Category',
    'admin.productSupplier': 'Supplier',
    'admin.productDescription': 'Description',
    'admin.productImage': 'Product Image',
    'admin.originalPrice': 'Original Price',
    'admin.costPrice': 'Cost Price',
    'admin.deleteProduct': 'Delete Product',
    'admin.confirmDelete': 'Are you sure you want to delete this?',
    
    // Admin Categories
    'admin.addCategory': 'Add Category',
    'admin.editCategory': 'Edit Category',
    'admin.categoryName': 'Category Name',
    'admin.categoryImage': 'Category Image',
    'admin.parentCategory': 'Parent Category',
    'admin.noParent': 'No Parent (Top Level)',
    
    // Admin Orders
    'admin.orderId': 'Order ID',
    'admin.customer': 'Customer',
    'admin.status': 'Status',
    'admin.date': 'Date',
    'admin.amount': 'Amount',
    'admin.pending': 'Pending',
    'admin.processing': 'Processing',
    'admin.shipped': 'Shipped',
    'admin.delivered': 'Delivered',
    'admin.cancelled': 'Cancelled',
    'admin.orderDetails': 'Order Details',
    'admin.updateStatus': 'Update Status',
    
    // Admin Suppliers
    'admin.addSupplier': 'Add Supplier',
    'admin.editSupplier': 'Edit Supplier',
    'admin.supplierName': 'Supplier Name',
    'admin.contactName': 'Contact Name',
    'admin.phone': 'Phone',
    'admin.addressLine': 'Address',
    
    // Admin Users/Customers
    'admin.userId': 'User ID',
    'admin.userName': 'Name',
    'admin.userEmail': 'Email',
    'admin.role': 'Role',
    'admin.joinedDate': 'Joined',
    
    // Admin Financial
    'admin.revenue': 'Revenue',
    'admin.expenses': 'Expenses',
    'admin.netProfit': 'Net Profit',
    'admin.taxAmount': 'Tax Amount',
    'admin.currentCycle': 'Current Cycle',
    'admin.pastCycles': 'Past Cycles',
    'admin.addExpense': 'Add Expense',
    'admin.closeCycle': 'Close Cycle',
    
    // Admin Home Layout
    'admin.homeLayoutTitle': 'Home Layout Settings',
    'admin.sectionEnabled': 'Enabled',
    'admin.sectionName': 'Section Name',
    'admin.showBadge': 'Show Badge',
    'admin.badgeText': 'Badge Text',
    'admin.manualSelection': 'Manual Selection',
    'admin.automaticSelection': 'Automatic Selection',
    'admin.selectProducts': 'Select Products',
    'admin.saveChanges': 'Save Changes',
    'admin.resetToDefault': 'Reset to Default',
    
    // Admin Files
    'admin.uploadFile': 'Upload File',
    'admin.fileName': 'File Name',
    'admin.fileSize': 'Size',
    'admin.fileType': 'Type',
    'admin.uploadDate': 'Upload Date',
    'admin.copyUrl': 'Copy URL',
    'admin.deleteFile': 'Delete',
    
    // Common Admin
    'admin.actions': 'Actions',
    'admin.noResults': 'No results found',
    'admin.searchPlaceholder': 'Search...',
    'admin.itemsPerPage': 'Items per page',
    'admin.showing': 'Showing',
    'admin.of': 'of',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.create': 'Create',
    'admin.update': 'Update',
    'admin.delete': 'Delete',
    'admin.edit': 'Edit',
    'admin.view': 'View',
    'admin.back': 'Back',
    
    // Admin Suppliers (extended)
    'admin.suppliersTitle': 'Suppliers',
    'admin.suppliersSubtitle': 'Manage your product suppliers and vendors',
    'admin.totalSuppliers': 'Total Suppliers',
    'admin.searchSuppliers': 'Search suppliers...',
    'admin.noSuppliersYet': 'No suppliers yet',
    'admin.noSuppliersFound': 'No suppliers found',
    'admin.addFirstSupplier': 'Add your first supplier to get started',
    'admin.tryAdjustSearch': 'Try adjusting your search',
    'admin.createSupplier': 'Create Supplier',
    'admin.updateSupplier': 'Update Supplier',
    'admin.supplierNameRequired': 'Supplier Name *',
    'admin.contactPerson': 'Contact Person',
    'admin.loadingSuppliers': 'Loading suppliers...',
    'admin.noContactInfo': 'No contact information',
    
    // Admin Users (extended)
    'admin.userManagement': 'User Management',
    'admin.userManagementSubtitle': 'Manage customers and administrators',
    'admin.totalUsers': 'Total Users',
    'admin.administrators': 'Administrators',
    'admin.searchUsers': 'Search users...',
    'admin.allUsers': 'All Users',
    'admin.admins': 'Admins',
    'admin.user': 'User',
    'admin.contact': 'Contact',
    'admin.location': 'Location',
    'admin.noUsersFound': 'No users found',
    'admin.tryAdjustFilters': 'Try adjusting your search or filter criteria',
    'admin.editUserProfile': 'Edit User Profile',
    'admin.fullName': 'Full Name',
    'admin.phoneNumber': 'Phone Number',
    'admin.address': 'Address',
    'admin.userRole': 'User Role',
    'admin.administrator': 'Administrator',
    'admin.loadingUsers': 'Loading users...',
    'admin.unnamedUser': 'Unnamed User',
    
    // Admin Financial (extended)
    'admin.financialManagement': 'Financial Management',
    'admin.financialSubtitle': 'Manage cycles, expenses, and track your profitability.',
    'admin.exportReport': 'Export Report',
    'admin.startNewCycle': 'Start New Cycle',
    'admin.newExpense': 'New Expense',
    'admin.activeCycle': 'Active Cycle',
    'admin.noActiveCycle': 'No Active Cycle',
    'admin.toPresent': 'to Present',
    'admin.currentRevenue': 'Current Revenue',
    'admin.currentExpenses': 'Current Expenses',
    'admin.estimatedTax': 'Estimated Tax',
    'admin.payouts': 'Payouts',
    'admin.analysis': 'Analysis',
    'admin.recentTransactions': 'Recent Transactions',
    'admin.viewAllTransactions': 'View All',
    'admin.expenseLog': 'Expense Log',
    'admin.expenseLogDesc': 'Detailed view of all operational expenses.',
    'admin.loadExpenseDashboard': 'Load Expense Dashboard',
    'admin.supplierPayouts': 'Supplier Payouts',
    'admin.supplierPayoutsDesc': 'Manage and approve payments to product suppliers.',
    'admin.viewPayoutStatus': 'View Payout Status',
    'admin.previousCycles': 'Previous Cycles',
    'admin.profit': 'Profit',
    'admin.rev': 'Rev',
    'admin.viewAllHistory': 'View All History',
    'admin.cycleControls': 'Cycle Controls',
    'admin.closeCurrentCycle': 'Close Current Cycle',
    'admin.financialProjection': 'Financial Projection',
    'admin.manageTaxSlabs': 'Manage Tax Slabs',
    'admin.loadingFinancial': 'Loading financial records...',
    'admin.margin': 'Margin',
    
    // Admin Categories Page
    'admin.availableCategories': 'Available Categories',
    'admin.totalCategories': 'Total Categories',
    'admin.withProducts': 'With Products',
    'admin.empty': 'Empty',
    'admin.noDescription': 'No description',
    'admin.noCategoriesFound': 'No categories found',
    'admin.tryAdjustingSearch': 'Try adjusting your search terms',
    'admin.getStartedCategories': 'Get started by adding your first category',
    'admin.addFirstCategory': 'Add First Category',
    'admin.deleteCategory': 'Delete Category',
    'admin.deleteCategoryConfirm': 'Are you sure you want to delete this category? Products in this category will become uncategorized.',
    'admin.categoryNameRequired': 'Name *',
    'admin.nameInEnglish': 'Name in English',
    'admin.nameInArabic': 'Name in Arabic',
    'admin.basicInformation': 'Basic Information',
    'admin.translations': 'Translations',
    'admin.descriptionInArabic': 'Description in Arabic',
    'admin.selectCategory': 'Select a category...',
    'admin.optionalDescription': 'Optional description',
    'admin.chooseFile': 'Choose File',
    'admin.takePhoto': 'Take Photo',
    'admin.pasteImageUrl': 'Or paste an image URL:',
    
    // Admin Home Layout (extended)
    'admin.visibilityControl': 'Visibility Control',
    'admin.visibilityControlDesc': 'Use the toggles below to hide or show specific sections on your main page. This is useful for clearing space during specific sales or removing sections if they have no products yet.',
    'admin.countdownBadge': 'Countdown Badge',
    'admin.manualProductSelection': 'Manual Product Selection',
    'admin.enabled': 'ENABLED',
    'admin.disabled': 'DISABLED',
    'admin.manual': 'MANUAL',
    'admin.automatic': 'AUTOMATIC',
    'admin.selectProductsToFeature': 'Select specific products to feature in this section.',
    'admin.selectProductsForBrowsing': 'Select specific products to show as browsing recommendations.',
    'admin.selectProductsForTrending': 'Select specific products to show as trending.',
    'admin.selectProductsForAccessories': 'Select specific products to show as PC accessories.',
    'admin.searchProducts': 'Search products...',
    'admin.noProductsFound': 'No products found',
    'admin.autoShowsDiscounted': 'Automatically shows all products with a discount (original price > current price).',
    'admin.autoShowsFirst10': 'Automatically shows the first 10 products as recommendations.',
    'admin.autoShowsOver50': 'Automatically shows products priced over E£50.',
    'admin.autoShowsPeripherals': 'Automatically shows products with category containing mouse, keyboard, or headphone.',
    'admin.subtitleText': 'Subtitle Text',
    'admin.buttonText': 'Button Text',
    'admin.visible': 'VISIBLE',
    'admin.hidden': 'HIDDEN',
    'admin.autoSyncingReady': 'Auto-Syncing Ready',
    'admin.realTimeUpdates': 'Real-time Updates',
    'admin.versioning': 'Versioning',
    'admin.sectionDescription': 'Section Description',
    'admin.enterBadgeText': 'Enter badge text (e.g. Ends in 12:34:56)',
    'admin.enterSubtitleText': 'Enter subtitle text',
    'admin.enterButtonText': 'Enter button text',
};

// Arabic translations
const ar: Record<string, string> = {
    // Header
    'header.deliverTo': 'التوصيل إلى',
    'header.location': 'القاهرة والجيزة',
    'header.searchPlaceholder': 'ابحث عن المنتجات...',
    'header.all': 'الكل',
    'header.hello': 'مرحباً',
    'header.signIn': 'تسجيل الدخول',
    'header.accountAndLists': 'الحساب والقوائم',
    'header.alerts': 'التنبيهات',
    'header.cart': 'السلة',
    'header.todaysDeals': 'عروض اليوم',
    'header.customerService': 'خدمة العملاء',
    'header.registry': 'السجل',
    'header.giftCards': 'بطاقات الهدايا',
    'header.sell': 'بيع',
    'header.home': 'الرئيسية',
    'header.browseProducts': 'تصفح المنتجات',
    'header.signOut': 'تسجيل الخروج',
    'header.createAccount': 'إنشاء حساب',
    'header.departments': 'الأقسام',
    'header.adminDashboard': 'لوحة التحكم',
    'header.newCustomer': 'عميل جديد؟',
    'header.createNewAccount': 'إنشاء حساب جديد',
    'header.yourAccount': 'حسابك',
    'header.yourOrders': 'طلباتك',
    'header.yourLists': 'قوائمك',

    // Categories
    'category.pcs': 'أجهزة الكمبيوتر',
    'category.laptops': 'أجهزة اللابتوب',
    'category.mice': 'الفأرات',
    'category.keyboards': 'لوحات المفاتيح',
    'category.headphones': 'سماعات الرأس',
    'category.cables': 'الكابلات',
    'category.mousePads': 'وسائد الماوس',
    'category.hardDrives': 'الأقراص الصلبة',
    'category.books': 'الكتب',
    'category.fashion': 'الموضة',
    'category.homeKitchen': 'المنزل والمطبخ',

    // Auth
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.signInToAccount': 'تسجيل الدخول إلى حسابك',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.signingIn': 'جاري تسجيل الدخول...',
    'auth.newCustomer': 'عميل جديد؟',
    'auth.createAccount': 'إنشاء حساب',
    'auth.emailVerified': 'تم التحقق من البريد الإلكتروني! يمكنك الآن تسجيل الدخول.',
    'auth.createYourAccount': 'إنشاء حسابك',
    'auth.joinUs': 'انضم إلينا اليوم',
    'auth.name': 'الاسم',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.creatingAccount': 'جاري إنشاء الحساب...',
    'auth.alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'auth.signInHere': 'تسجيل الدخول هنا',

    // Home Page
    'home.shopByCategory': 'تسوق حسب الفئة',
    'home.viewAll': 'عرض الكل',
    'home.dealsOfTheDay': 'عروض اليوم',
    'home.seeAllDeals': 'عرض جميع العروض',
    'home.inspiredByHistory': 'مستوحى من سجل تصفحك',
    'home.trendingInElectronics': 'الأكثر رواجاً في الإلكترونيات',
    'home.signUpForBestExperience': 'سجل للحصول على أفضل تجربة',
    'home.signUp': 'سجل الآن',
    'home.pcAccessories': 'إكسسوارات الكمبيوتر والملحقات',
    'home.topRatedProducts': 'المنتجات الأعلى تقييماً',
    'home.shopNow': 'تسوق الآن',

    // Product
    'product.addToCart': 'أضف إلى السلة',
    'product.buyNow': 'اشتري الآن',
    'product.inStock': 'متوفر',
    'product.outOfStock': 'غير متوفر',
    'product.prime': 'برايم',
    'product.freeDelivery': 'توصيل مجاني',
    'product.tomorrow': 'غداً',
    'product.quantity': 'الكمية',
    'product.reviews': 'تقييمات',
    'product.rating': 'تقييم',
    'product.price': 'السعر',
    'product.originalPrice': 'السعر الأصلي',
    'product.savings': 'وفرت',
    'product.description': 'الوصف',
    'product.specifications': 'المواصفات',
    'product.customerReviews': 'تقييمات العملاء',

    // Cart
    'cart.shoppingCart': 'سلة التسوق',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.items': 'منتجات',
    'cart.proceedToCheckout': 'متابعة الدفع',
    'cart.continueShopping': 'متابعة التسوق',
    'cart.remove': 'إزالة',
    'cart.price': 'السعر',
    'cart.qty': 'الكمية',

    // Checkout
    'checkout.secureCheckout': 'الدفع الآمن',
    'checkout.checkout': 'الدفع',
    'checkout.shippingAddress': 'عنوان الشحن',
    'checkout.paymentMethod': 'طريقة الدفع',
    'checkout.reviewOrder': 'مراجعة المنتجات والشحن',
    'checkout.fullName': 'الاسم الكامل',
    'checkout.address': 'العنوان',
    'checkout.city': 'المدينة',
    'checkout.state': 'المحافظة',
    'checkout.zipCode': 'الرمز البريدي',
    'checkout.phone': 'رقم الهاتف',
    'checkout.continueToPayment': 'متابعة للدفع',
    'checkout.change': 'تغيير',
    'checkout.creditCard': 'بطاقة ائتمان أو خصم',
    'checkout.paypal': 'باي بال',
    'checkout.giftCard': 'بطاقة هدايا',
    'checkout.cardNumber': 'رقم البطاقة',
    'checkout.nameOnCard': 'الاسم على البطاقة',
    'checkout.expirationDate': 'تاريخ الانتهاء',
    'checkout.securityCode': 'رمز الأمان',
    'checkout.continue': 'متابعة',
    'checkout.shippingSpeed': 'اختر سرعة الشحن:',
    'checkout.freeDelivery': 'توصيل مجاني',
    'checkout.standardDelivery': 'توصيل عادي',
    'checkout.expressDelivery': 'توصيل سريع',
    'checkout.arrives': 'يصل',
    'checkout.tomorrow': 'غداً',
    'checkout.itemsInOrder': 'المنتجات في طلبك:',
    'checkout.placeOrder': 'تأكيد الطلب',
    'checkout.orderSummary': 'ملخص الطلب',
    'checkout.shippingHandling': 'الشحن والتوصيل',
    'checkout.estimatedTax': 'الضريبة المقدرة',
    'checkout.orderTotal': 'إجمالي الطلب',
    'checkout.free': 'مجاني',
    'checkout.agreeTerms': 'بتأكيد طلبك، فإنك توافق على سياسة الخصوصية وشروط الاستخدام.',

    // Order Confirmation
    'confirmation.orderPlaced': 'تم تأكيد الطلب بنجاح!',
    'confirmation.thankYou': 'شكراً لطلبك!',
    'confirmation.emailConfirmation': 'ستتلقى تأكيداً بالبريد الإلكتروني قريباً.',
    'confirmation.orderDetails': 'تفاصيل الطلب',
    'confirmation.orderNumber': 'رقم الطلب',
    'confirmation.orderDate': 'تاريخ الطلب',
    'confirmation.estimatedDelivery': 'التوصيل المتوقع',
    'confirmation.viewOrders': 'عرض الطلبات',

    // Footer
    'footer.getToKnowUs': 'تعرف علينا',
    'footer.aboutUs': 'من نحن',
    'footer.careers': 'الوظائف',
    'footer.pressReleases': 'البيانات الصحفية',
    'footer.makeMoneyWithUs': 'اربح معنا',
    'footer.sellOnShop': 'بيع على المتجر',
    'footer.becomeAffiliate': 'كن شريكاً',
    'footer.advertiseProducts': 'أعلن عن منتجاتك',
    'footer.paymentProducts': 'منتجات الدفع',
    'footer.shopCard': 'بطاقة المتجر',
    'footer.currencyConverter': 'محول العملات',
    'footer.letUsHelpYou': 'دعنا نساعدك',
    'footer.returnsCenter': 'مركز الإرجاع',
    'footer.help': 'المساعدة',
    'footer.copyright': '© 2026 Shop.com، جميع الحقوق محفوظة',

    // About Us Page
    'aboutUs.title': 'من نحن',
    'aboutUs.subtitle': 'نبني مستقبل التجارة الإلكترونية في الشرق الأوسط',
    'aboutUs.ourMission': 'مهمتنا',
    'aboutUs.missionText1': 'نحن ملتزمون بتقديم أفضل تجربة تسوق عبر الإنترنت من خلال توفير مجموعة واسعة من المنتجات عالية الجودة بأسعار تنافسية مع توصيل سريع وموثوق.',
    'aboutUs.missionText2': 'نؤمن بوضع عملائنا في المقام الأول والابتكار المستمر لتلبية احتياجاتهم المتطورة في العصر الرقمي.',
    'aboutUs.ourValues': 'قيمنا',
    'aboutUs.customerFirst': 'العميل أولاً',
    'aboutUs.customerFirstDesc': 'كل قرار نتخذه يبدأ بعملائنا في الاعتبار',
    'aboutUs.innovation': 'الابتكار',
    'aboutUs.innovationDesc': 'التحسين المستمر واعتماد التقنيات الجديدة',
    'aboutUs.trust': 'الثقة والنزاهة',
    'aboutUs.trustDesc': 'بناء علاقات دائمة من خلال الممارسات الصادقة',
    'aboutUs.sustainability': 'الاستدامة',
    'aboutUs.sustainabilityDesc': 'ملتزمون بعمليات مسؤولة بيئياً',
    'aboutUs.ourJourney': 'رحلتنا',
    'aboutUs.milestone2015': 'التأسيس',
    'aboutUs.milestone2015Desc': 'بدأنا كمتجر إلكترونيات صغير في القاهرة',
    'aboutUs.milestone2017': 'التوسع',
    'aboutUs.milestone2017Desc': 'توسعنا لتغطية جميع المدن الرئيسية في مصر',
    'aboutUs.milestone2019': 'الجوال أولاً',
    'aboutUs.milestone2019Desc': 'أطلقنا تطبيق الجوال بأكثر من مليون تحميل',
    'aboutUs.milestone2021': 'النمو الإقليمي',
    'aboutUs.milestone2021Desc': 'توسعنا في السعودية والإمارات',
    'aboutUs.milestone2023': '10 مليون عميل',
    'aboutUs.milestone2023Desc': 'وصلنا إلى 10 ملايين عميل نشط',
    'aboutUs.milestone2025': 'تكامل الذكاء الاصطناعي',
    'aboutUs.milestone2025Desc': 'قدمنا توصيات تسوق مدعومة بالذكاء الاصطناعي',
    'aboutUs.leadershipTeam': 'فريق القيادة',
    'aboutUs.roleCEO': 'الرئيس التنفيذي',
    'aboutUs.roleCTO': 'الرئيس التقني',
    'aboutUs.roleCOO': 'رئيس العمليات',
    'aboutUs.roleCMO': 'رئيس التسويق',
    'aboutUs.awardsTitle': 'الجوائز والتقدير',
    'aboutUs.award1': 'أفضل منصة تجارة إلكترونية',
    'aboutUs.award2': 'جائزة التميز في خدمة العملاء',
    'aboutUs.award3': 'الابتكار في التجزئة',
    'aboutUs.statCustomers': 'العملاء النشطين',
    'aboutUs.statCountries': 'الدول المخدومة',
    'aboutUs.statProducts': 'المنتجات المتاحة',
    'aboutUs.statSupport': 'دعم العملاء',

    // Careers Page
    'careers.title': 'انضم إلى فريقنا',
    'careers.subtitle': 'ابنِ مسيرتك المهنية في واحدة من أسرع شركات التجارة الإلكترونية نمواً',
    'careers.searchPlaceholder': 'ابحث عن الوظائف...',
    'careers.whyJoinUs': 'لماذا تنضم إلينا',
    'careers.benefitHealth': 'الصحة والعافية',
    'careers.benefitHealthDesc': 'تأمين صحي شامل لك ولعائلتك',
    'careers.benefitLearning': 'التعلم والتطوير',
    'careers.benefitLearningDesc': 'ميزانية تعليم سنوية ودورات عبر الإنترنت',
    'careers.benefitBalance': 'التوازن بين العمل والحياة',
    'careers.benefitBalanceDesc': 'ساعات مرنة وخيارات العمل عن بعد',
    'careers.benefitGrowth': 'النمو الوظيفي',
    'careers.benefitGrowthDesc': 'مسارات واضحة للتقدم وبرامج الإرشاد',
    'careers.lifeAtShop': 'الحياة في Shop.com',
    'careers.lifeAtShopText1': 'نحن فريق متنوع من الأشخاص المتحمسين نعمل معاً لتحويل التجارة الإلكترونية في المنطقة.',
    'careers.lifeAtShopText2': 'ثقافتنا تحتفي بالابتكار والتعاون والنمو الشخصي. نؤمن بأن الموظفين السعداء يصنعون عملاء سعداء.',
    'careers.openPositions': 'الوظائف المتاحة',
    'careers.allDepartments': 'جميع الأقسام',
    'careers.engineering': 'الهندسة',
    'careers.product': 'المنتج',
    'careers.marketing': 'التسويق',
    'careers.operations': 'العمليات',
    'careers.customerService': 'خدمة العملاء',
    'careers.noJobsFound': 'لم يتم العثور على وظائف تطابق معاييرك',
    'careers.applyNow': 'قدم الآن',
    'careers.dontSeeRole': 'لا ترى دورك؟',
    'careers.dontSeeRoleText': 'نحن دائماً نبحث عن المواهب. أرسل لنا سيرتك الذاتية وسنضعك في اعتبارنا للفرص المستقبلية.',
    'careers.sendResume': 'أرسل سيرتك الذاتية',

    // Press Releases Page
    'press.title': 'البيانات الصحفية',
    'press.subtitle': 'آخر الأخبار والإعلانات من Shop.com',
    'press.featured': 'مميز',
    'press.latestNews': 'آخر الأخبار',
    'press.filterByYear': 'تصفية حسب السنة',
    'press.newsFrom': 'أخبار من',
    'press.releases': 'بيانات',
    'press.noReleases': 'لا توجد بيانات صحفية لهذا العام',
    'press.readMore': 'اقرأ المزيد',
    'press.mediaContacts': 'جهات اتصال الإعلام',
    'press.mediaKit': 'الحقيبة الإعلامية',
    'press.mediaKitDesc': 'حمّل أصول علامتنا التجارية والشعارات وصحيفة الحقائق للتغطية الصحفية.',
    'press.downloadKit': 'تحميل الحقيبة الإعلامية',
    'press.release1Title': 'Shop.com يعلن عن مبيعات قياسية خلال موسم العطلات',
    'press.release1Summary': 'منصة التجارة الإلكترونية تسجل زيادة 150% في المبيعات مقارنة بالعام السابق خلال موسم العطلات.',
    'press.release2Title': 'إطلاق خدمة التوصيل في نفس اليوم في القاهرة',
    'press.release2Summary': 'يمكن لعملاء القاهرة الآن استلام طلباتهم خلال ساعات مع خيار التوصيل السريع الجديد.',
    'press.release3Title': 'Shop.com يتشارك مع علامات إلكترونيات رائدة',
    'press.release3Summary': 'الشراكات الاستراتيجية تجلب منتجات حصرية وأسعار أفضل لعملائنا.',
    'press.release4Title': 'تطبيق الجوال يصل إلى 5 ملايين تحميل',
    'press.release4Summary': 'تطبيق التسوق لدينا يستمر في النمو مع ميزات محسّنة وتجربة مستخدم أفضل.',
    'press.release5Title': 'Shop.com يفوز بجائزة أفضل منصة تجارة إلكترونية',
    'press.release5Summary': 'تم تكريمه للابتكار والتميز في خدمة العملاء في جوائز التقنية لمنطقة الشرق الأوسط.',
    'press.release6Title': 'توسيع شبكة المستودعات',
    'press.release6Summary': 'افتتاح مراكز توزيع جديدة في الإسكندرية وأسوان لتوصيل إقليمي أسرع.',
    'press.release7Title': 'إطلاق بطاقة ائتمان Shop.com',
    'press.release7Summary': 'البطاقة الجديدة المشتركة تقدم استرداد نقدي حصري وخيارات تمويل للعملاء.',
    'press.release8Title': 'Shop.com يحتفل بمليون بائع نشط',
    'press.release8Summary': 'إنجاز السوق يعكس الثقة المتزايدة في نظام البائعين لدينا.',

    // Affiliate Page
    'affiliate.title': 'برنامج الشراكة',
    'affiliate.subtitle': 'اكسب عمولات من خلال مشاركة المنتجات التي تحبها مع جمهورك',
    'affiliate.joinNow': 'انضم الآن',
    'affiliate.learnMore': 'اعرف المزيد',
    'affiliate.earnWhileYouShare': 'اكسب أثناء المشاركة',
    'affiliate.earnWhileYouShareDesc': 'حوّل محتواك إلى دخل من خلال توصية المنتجات لمتابعيك',
    'affiliate.whyJoin': 'لماذا تنضم لبرنامجنا؟',
    'affiliate.earnCommissions': 'اكسب عمولات',
    'affiliate.earnCommissionsDesc': 'احصل على ما يصل إلى 12% على المشتريات المؤهلة',
    'affiliate.trackPerformance': 'تتبع الأداء',
    'affiliate.trackPerformanceDesc': 'لوحة تحكم فورية لمراقبة النقرات والأرباح',
    'affiliate.easySharing': 'مشاركة سهلة',
    'affiliate.easySharingDesc': 'أنشئ روابط ولافتات وأدوات في ثوانٍ',
    'affiliate.dedicatedSupport': 'دعم مخصص',
    'affiliate.dedicatedSupportDesc': 'فريق خبراء لمساعدتك في زيادة الأرباح',
    'affiliate.commissionRates': 'معدلات العمولة',
    'affiliate.tierElectronics': 'الإلكترونيات',
    'affiliate.tierFashion': 'الأزياء',
    'affiliate.tierHome': 'المنزل والمطبخ',
    'affiliate.tierBooks': 'الكتب',
    'affiliate.tierBeauty': 'الجمال',
    'affiliate.tierSports': 'الرياضة',
    'affiliate.ratesDisclaimer': 'قد تختلف معدلات العمولة حسب الفئة وفترات العروض',
    'affiliate.howItWorks': 'كيف يعمل',
    'affiliate.step1Title': 'سجّل مجاناً',
    'affiliate.step1Desc': 'أنشئ حساب الشراكة الخاص بك في دقائق',
    'affiliate.step2Title': 'شارك المنتجات',
    'affiliate.step2Desc': 'أنشئ روابط فريدة للمنتجات التي تحبها',
    'affiliate.step3Title': 'اكسب المال',
    'affiliate.step3Desc': 'احصل على أموال مقابل كل عملية شراء مؤهلة',
    'affiliate.step4Title': 'استلم الدفع',
    'affiliate.step4Desc': 'استلم المدفوعات شهرياً عبر التحويل البنكي',
    'affiliate.startEarning': 'مستعد لبدء الكسب؟',
    'affiliate.joinFree': 'انضم لبرنامج الشراكة مجاناً اليوم',
    'affiliate.firstName': 'الاسم الأول',
    'affiliate.lastName': 'اسم العائلة',
    'affiliate.email': 'البريد الإلكتروني',
    'affiliate.website': 'الموقع أو وسائل التواصل',
    'affiliate.audience': 'حجم الجمهور',
    'affiliate.selectAudience': 'اختر حجم جمهورك',
    'affiliate.createAccount': 'إنشاء حساب شراكة',
    'affiliate.termsAgreement': 'بالتسجيل، أنت توافق على شروط وأحكام الشراكة',
    'affiliate.faq': 'الأسئلة الشائعة',
    'affiliate.faq1': 'كيف أحصل على الدفع؟',
    'affiliate.faq1Answer': 'تتم المدفوعات شهرياً عبر التحويل البنكي بمجرد الوصول للحد الأدنى 100 جنيه.',
    'affiliate.faq2': 'كم تدوم ملفات تعريف الارتباط؟',
    'affiliate.faq2Answer': 'ملفات تعريف الارتباط لدينا تدوم 30 يوماً، لذا تكسب عمولات على المشتريات خلال تلك الفترة.',
    'affiliate.faq3': 'هل يمكنني الترويج على وسائل التواصل الاجتماعي؟',
    'affiliate.faq3Answer': 'نعم! يمكنك مشاركة روابط الشراكة على المدونات ويوتيوب وإنستغرام وتيك توك ومنصات أخرى.',
    'affiliate.faq4': 'هل هناك حد أدنى لمتطلبات الجمهور؟',
    'affiliate.faq4Answer': 'لا يوجد حد أدنى مطلوب، لكن الجماهير الأكبر عادة تكسب عمولات أكثر.',
    'affiliate.statPaid': 'مدفوع للشركاء',
    'affiliate.statAffiliates': 'شركاء نشطين',
    'affiliate.statAvgCommission': 'متوسط العمولة',
    'affiliate.statCookieDays': 'مدة ملفات الارتباط (أيام)',

    // Advertise Page
    'advertise.title': 'أعلن عن منتجاتك',
    'advertise.subtitle': 'وصل لملايين المتسوقين الذين يبحثون بنشاط عن الشراء',
    'advertise.getStarted': 'ابدأ الآن',
    'advertise.contactSales': 'تواصل مع المبيعات',
    'advertise.reachYourCustomers': 'وصل لعملائك',
    'advertise.reachYourCustomersDesc': 'استهدف المتسوقين بناءً على اهتماماتهم وسجل البحث وسلوك الشراء',
    'advertise.adSolutions': 'حلول الإعلان',
    'advertise.sponsoredProducts': 'المنتجات المروجة',
    'advertise.sponsoredProductsDesc': 'روّج للقوائم الفردية في نتائج البحث وصفحات المنتجات',
    'advertise.sponsoredBrands': 'العلامات التجارية المروجة',
    'advertise.sponsoredBrandsDesc': 'اعرض علامتك التجارية مع عناوين مخصصة ومنتجات متعددة',
    'advertise.displayAds': 'إعلانات العرض',
    'advertise.displayAdsDesc': 'وصل للعملاء عبر موقعنا بإعلانات بصرية',
    'advertise.featurePayPerClick': 'تسعير الدفع بالنقرة',
    'advertise.featureKeywordTargeting': 'استهداف الكلمات المفتاحية',
    'advertise.featureAutoOptimization': 'تحسين الحملة تلقائياً',
    'advertise.featureCustomHeadline': 'عنوان مخصص',
    'advertise.featureBrandLogo': 'عرض شعار العلامة',
    'advertise.featureMultipleProducts': 'عرض منتجات متعددة',
    'advertise.featureAudienceTargeting': 'استهداف الجمهور',
    'advertise.featureRetargeting': 'إمكانيات إعادة الاستهداف',
    'advertise.featureRichMedia': 'دعم الوسائط الغنية',
    'advertise.learnMore': 'اعرف المزيد',
    'advertise.howItWorks': 'كيف يعمل',
    'advertise.step1Title': 'أنشئ حملة',
    'advertise.step1Desc': 'أعد حملتك واختر المنتجات للترويج',
    'advertise.step2Title': 'حدد الميزانية',
    'advertise.step2Desc': 'حدد ميزانية يومية أو إجمالية للحملة',
    'advertise.step3Title': 'استهدف الجمهور',
    'advertise.step3Desc': 'اختر الكلمات المفتاحية والتركيبة السكانية والاهتمامات',
    'advertise.step4Title': 'أطلق وحسّن',
    'advertise.step4Desc': 'انطلق وراقب الأداء في الوقت الفعلي',
    'advertise.successStories': 'قصص النجاح',
    'advertise.testimonial1': 'ساعدتنا المنتجات المروجة في الوصول لعملاء جدد وزيادة المبيعات بنسبة 250% في 3 أشهر فقط.',
    'advertise.testimonial2': 'خيارات الاستهداف مذهلة. شهدنا زيادة هائلة في الوعي بالعلامة التجارية.',
    'advertise.testimonial3': 'جلبت إعلانات العرض حركة مرور كبيرة لمتجرنا، مع معدلات تحويل ممتازة.',
    'advertise.startAdvertising': 'ابدأ الإعلان اليوم',
    'advertise.contactUsToday': 'املأ النموذج وسيتواصل فريقنا معك خلال 24 ساعة',
    'advertise.companyName': 'اسم الشركة',
    'advertise.contactName': 'اسم جهة الاتصال',
    'advertise.email': 'البريد الإلكتروني',
    'advertise.phone': 'الهاتف',
    'advertise.monthlyBudget': 'ميزانية الإعلان الشهرية',
    'advertise.selectBudget': 'اختر نطاق ميزانيتك',
    'advertise.message': 'الرسالة',
    'advertise.messagePlaceholder': 'أخبرنا عن أهدافك الإعلانية...',
    'advertise.submitInquiry': 'إرسال الاستفسار',
    'advertise.statActiveShoppers': 'متسوقين نشطين',
    'advertise.statAvgROI': 'متوسط العائد على الاستثمار',
    'advertise.statMinCPC': 'الحد الأدنى لتكلفة النقرة',
    'advertise.statCampaignApproval': 'الموافقة على الحملة',

    // Shop Card Page
    'shopCard.title': 'بطاقة المتجر',
    'shopCard.subtitle': 'الطريقة الذكية للتسوق - اكسب استرداد نقدي على كل عملية شراء',
    'shopCard.applyNow': 'قدم الآن',
    'shopCard.learnMore': 'اعرف المزيد',
    'shopCard.cardHolder': 'حامل البطاقة',
    'shopCard.cardBenefits': 'مزايا البطاقة',
    'shopCard.cashback': 'استرداد نقدي حتى 7%',
    'shopCard.cashbackDesc': 'اكسب استرداد نقدي على كل عملية شراء في Shop.com',
    'shopCard.welcomeBonus': 'مكافأة الترحيب',
    'shopCard.welcomeBonusDesc': 'احصل على مكافأة 500 جنيه على أول عملية شراء',
    'shopCard.nannualFee': 'بدون رسوم سنوية',
    'shopCard.noAnnualFeeDesc': 'صفر رسوم - لا رسوم خفية على الإطلاق',
    'shopCard.secureShopping': 'تسوق آمن',
    'shopCard.secureShoppingDesc': 'محمية بمنع الاحتيال المتقدم',
    'shopCard.cashbackTiers': 'مستويات الاسترداد النقدي',
    'shopCard.tierBasic': 'أساسي',
    'shopCard.tierSilver': 'فضي',
    'shopCard.tierGold': 'ذهبي',
    'shopCard.tierPlatinum': 'بلاتيني',
    'shopCard.cashbackLabel': 'استرداد نقدي',
    'shopCard.minSpend': 'الحد الأدنى للإنفاق السنوي',
    'shopCard.allFeatures': 'جميع مميزات البطاقة',
    'shopCard.feature1': 'موافقة فورية وبطاقة رقمية',
    'shopCard.feature2': 'عروض حصرية للأعضاء فقط',
    'shopCard.feature3': 'شحن سريع مجاني للطلبات فوق 500 جنيه',
    'shopCard.feature4': 'ضمان ممتد على الإلكترونيات',
    'shopCard.feature5': 'دعم عملاء ذو أولوية',
    'shopCard.feature6': 'خيارات تقسيط سهلة حتى 24 شهر',
    'shopCard.rewardsBalance': 'رصيد المكافآت الخاص بك',
    'shopCard.rewardsBalanceDesc': 'يمكن استبدال المكافآت بمشتريات أو تحويلها لبنكك',
    'shopCard.redeemRewards': 'استبدال المكافآت',
    'shopCard.applyForCard': 'قدم للحصول على بطاقة المتجر',
    'shopCard.quickApproval': 'احصل على الموافقة في دقائق - لا حاجة لأوراق',
    'shopCard.fullName': 'الاسم الكامل',
    'shopCard.email': 'البريد الإلكتروني',
    'shopCard.phone': 'رقم الهاتف',
    'shopCard.nationalId': 'رقم الهوية الوطنية',
    'shopCard.monthlyIncome': 'الدخل الشهري',
    'shopCard.selectIncome': 'اختر نطاق دخلك',
    'shopCard.agreeTerms': 'أوافق على الشروط والأحكام وسياسة الخصوصية',
    'shopCard.submitApplication': 'تقديم الطلب',
    'shopCard.secureApplication': 'معلوماتك آمنة ومشفرة',
    'shopCard.faq': 'الأسئلة الشائعة',
    'shopCard.faq1': 'كيف أكسب الاسترداد النقدي؟',
    'shopCard.faq1Answer': 'يتم إيداع الاسترداد النقدي تلقائياً في حسابك بعد كل عملية شراء. المستويات الأعلى تكسب استرداد نقدي أكثر.',
    'shopCard.faq2': 'هل يمكنني استخدام البطاقة خارج Shop.com؟',
    'shopCard.faq2Answer': 'بطاقة المتجر حصرية للمشتريات على Shop.com. للمشتريات الخارجية، تكسب 1% استرداد نقدي.',
    'shopCard.faq3': 'كم يستغرق الموافقة؟',
    'shopCard.faq3Answer': 'معظم الطلبات يتم الموافقة عليها في دقائق. ستستلم بطاقتك الرقمية فوراً عند الموافقة.',

    // Currency Converter Page
    'currency.title': 'محول العملات',
    'currency.subtitle': 'حوّل العملات وشاهد الأسعار بعملتك المفضلة',
    'currency.convertNow': 'تحويل العملة',
    'currency.amount': 'المبلغ',
    'currency.from': 'من',
    'currency.to': 'إلى',
    'currency.rateDisclaimer': 'الأسعار للرجوع فقط وقد تختلف عن أسعار المعاملات الفعلية',
    'currency.popularRates': 'أسعار الصرف الشائعة',
    'currency.whyUseOurs': 'لماذا تستخدم محولنا؟',
    'currency.featureRealTime': 'أسعار فورية',
    'currency.featureRealTimeDesc': 'أسعار الصرف محدثة كل دقيقة',
    'currency.featureSecure': 'آمن وموثوق',
    'currency.featureSecureDesc': 'موثوق به من ملايين المستخدمين',
    'currency.featureGlobal': 'تغطية عالمية',
    'currency.featureGlobalDesc': 'دعم أكثر من 150 عملة',
    'currency.featureFast': 'سريع وسهل',
    'currency.featureFastDesc': 'حوّل في ثوانٍ',
    'currency.howToUse': 'كيفية الاستخدام عند الدفع',
    'currency.step1Title': 'اختر العملة',
    'currency.step1Desc': 'اختر عملتك المفضلة في إعدادات حسابك',
    'currency.step2Title': 'تسوق بشكل طبيعي',
    'currency.step2Desc': 'تصفح وأضف العناصر لسلتك كالعادة',
    'currency.step3Title': 'ادفع بعملتك',
    'currency.step3Desc': 'شاهد الأسعار وادفع بعملتك المختارة عند الدفع',
    'currency.noHiddenFees': 'لا رسوم تحويل خفية',
    'currency.noHiddenFeesDesc': 'السعر الذي تراه هو السعر الذي تدفعه - لا رسوم مفاجئة',
    'currency.egyptianPound': 'الجنيه المصري',
    'currency.usDollar': 'الدولار الأمريكي',
    'currency.euro': 'اليورو',
    'currency.britishPound': 'الجنيه الإسترليني',
    'currency.saudiRiyal': 'الريال السعودي',
    'currency.uaeDirham': 'الدرهم الإماراتي',
    'currency.kuwaitiDinar': 'الدينار الكويتي',
    'currency.qatariRiyal': 'الريال القطري',
    'currency.bahrainiDinar': 'الدينار البحريني',
    'currency.omaniRial': 'الريال العماني',
    'currency.jordanianDinar': 'الدينار الأردني',

    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.update': 'تحديث',
    'common.create': 'إنشاء',
    'common.edit': 'تعديل',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.apply': 'تطبيق',
    'common.clear': 'مسح',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.close': 'إغلاق',
    'common.submit': 'إرسال',
    'common.signInRequired': 'يرجى تسجيل الدخول لمتابعة الدفع',

    // Customer Service
    'customerService.title': 'خدمة العملاء',
    'customerService.howCanWeHelp': 'كيف يمكننا مساعدتك؟',
    'customerService.searchHelp': 'ابحث في مكتبة المساعدة أو تصفح حسب الفئة',
    'customerService.searchPlaceholder': 'صف مشكلتك...',
    'customerService.quickLinks': 'روابط سريعة',
    'customerService.trackPackage': 'تتبع الطرد',
    'customerService.trackPackageDesc': 'تحقق من حالة طلباتك',
    'customerService.returnsRefunds': 'الإرجاع والاسترداد',
    'customerService.returnsRefundsDesc': 'إرجاع أو استبدال المنتجات',
    'customerService.paymentSettings': 'إعدادات الدفع',
    'customerService.paymentSettingsDesc': 'إدارة طرق الدفع',
    'customerService.accountSecurity': 'أمان الحساب',
    'customerService.accountSecurityDesc': 'تحديث كلمة المرور والإعدادات',
    'customerService.deliveryIssues': 'مشاكل التوصيل',
    'customerService.deliveryIssuesDesc': 'الإبلاغ عن مشاكل التوصيل',
    'customerService.contactUs': 'تواصل معنا',
    'customerService.contactUsDesc': 'تحدث مع دعم العملاء',
    'customerService.browseByTopic': 'تصفح حسب الموضوع',
    'customerService.ordersShipping': 'الطلبات والشحن',
    'customerService.ordersShippingQ1': 'كيف أتتبع طلبي؟',
    'customerService.ordersShippingQ2': 'ما هي خيارات الشحن؟',
    'customerService.ordersShippingQ3': 'هل يمكنني تغيير عنوان الشحن؟',
    'customerService.ordersShippingQ4': 'كم يستغرق التوصيل؟',
    'customerService.returnsRefundsSection': 'الإرجاع والاسترداد',
    'customerService.returnsRefundsQ1': 'كيف أرجع منتجاً؟',
    'customerService.returnsRefundsQ2': 'ما هي سياسة الإرجاع؟',
    'customerService.returnsRefundsQ3': 'متى سأحصل على استردادي؟',
    'customerService.returnsRefundsQ4': 'هل يمكنني استبدال منتج؟',
    'customerService.accountSecuritySection': 'الحساب والأمان',
    'customerService.accountSecurityQ1': 'كيف أعيد تعيين كلمة المرور؟',
    'customerService.accountSecurityQ2': 'كيف أحدث بريدي الإلكتروني؟',
    'customerService.accountSecurityQ3': 'هل معلومات الدفع الخاصة بي آمنة؟',
    'customerService.accountSecurityQ4': 'كيف أحذف حسابي؟',
    'customerService.paymentPricing': 'الدفع والأسعار',
    'customerService.paymentPricingQ1': 'ما طرق الدفع المقبولة؟',
    'customerService.paymentPricingQ2': 'لماذا تم احتساب ضريبة المبيعات؟',
    'customerService.paymentPricingQ3': 'هل تقدمون مطابقة الأسعار؟',
    'customerService.paymentPricingQ4': 'كيف أستخدم بطاقة الهدايا؟',
    'customerService.stillNeedHelp': 'هل ما زلت بحاجة للمساعدة؟',
    'customerService.liveChat': 'المحادثة المباشرة',
    'customerService.liveChatDesc': 'تحدث مع فريق الدعم',
    'customerService.startChat': 'ابدأ المحادثة',
    'customerService.phoneSupport': 'الدعم الهاتفي',
    'customerService.phoneSupportDesc': 'اتصل بنا: 1-800-123-4567',
    'customerService.requestCallback': 'طلب اتصال',
    'customerService.emailSupport': 'الدعم بالبريد الإلكتروني',
    'customerService.emailSupportDesc': 'احصل على المساعدة عبر البريد الإلكتروني',
    'customerService.sendEmail': 'إرسال بريد',
    'customerService.lookingForOrders': 'تبحث عن طلباتك؟',
    'customerService.lookingForOrdersDesc': 'عرض حالة الطلب ومعلومات التتبع والمزيد',
    'customerService.viewOrders': 'عرض الطلبات',

    // Gift Cards
    'giftCards.title': 'بطاقات الهدايا',
    'giftCards.subtitle': 'الهدية المثالية لأي مناسبة. اختر من ملايين المنتجات.',
    'giftCards.createYourGiftCard': 'أنشئ بطاقة هديتك',
    'giftCards.design': '1. التصميم',
    'giftCards.amount': '2. المبلغ',
    'giftCards.delivery': '3. التوصيل',
    'giftCards.chooseDesign': 'اختر تصميماً',
    'giftCards.birthdayCelebration': 'احتفال عيد الميلاد',
    'giftCards.birthday': 'عيد ميلاد',
    'giftCards.thankYou': 'شكراً لك',
    'giftCards.congratulations': 'تهانينا',
    'giftCards.celebration': 'احتفال',
    'giftCards.holidaySpecial': 'عطلة مميزة',
    'giftCards.holiday': 'عطلة',
    'giftCards.classicBlue': 'أزرق كلاسيكي',
    'giftCards.classic': 'كلاسيكي',
    'giftCards.weddingGift': 'هدية زفاف',
    'giftCards.wedding': 'زفاف',
    'giftCards.selectAmount': 'اختر المبلغ',
    'giftCards.enterCustomAmount': 'أو أدخل مبلغاً مخصصاً',
    'giftCards.minMaxAmount': 'الحد الأدنى: 1 ج.م | الحد الأقصى: 2,000 ج.م',
    'giftCards.deliveryMethod': 'طريقة التوصيل',
    'giftCards.email': 'البريد الإلكتروني',
    'giftCards.instantDelivery': 'توصيل فوري',
    'giftCards.textMessage': 'رسالة نصية',
    'giftCards.deliveredInMinutes': 'تصل في دقائق',
    'giftCards.physicalCard': 'بطاقة فعلية',
    'giftCards.shipsInDays': 'تشحن في 3-5 أيام عمل (+ 5.99 ج.م)',
    'giftCards.recipientEmail': 'بريد المستلم',
    'giftCards.yourName': 'اسمك',
    'giftCards.personalMessage': 'رسالة شخصية (اختياري)',
    'giftCards.addPersonalMessage': 'أضف رسالة شخصية...',
    'giftCards.deliveryDate': 'تاريخ التوصيل',
    'giftCards.orderSummary': 'ملخص الطلب',
    'giftCards.giftCard': 'بطاقة هدية',
    'giftCards.cardValue': 'قيمة البطاقة:',
    'giftCards.deliveryLabel': 'التوصيل:',
    'giftCards.free': 'مجاني',
    'giftCards.total': 'الإجمالي:',
    'giftCards.addToCart': 'أضف للسلة',
    'giftCards.continueShopping': 'متابعة التسوق',
    'giftCards.whyChoose': 'لماذا تختار بطاقات الهدايا لدينا؟',
    'giftCards.instantDeliveryTitle': 'توصيل فوري',
    'giftCards.instantDeliveryDesc': 'بطاقات الهدايا بالبريد الإلكتروني تصل في دقائق',
    'giftCards.noFees': 'بدون رسوم',
    'giftCards.noFeesDesc': 'لا رسوم شراء أو عدم نشاط',
    'giftCards.neverExpires': 'لا تنتهي صلاحيتها',
    'giftCards.neverExpiresDesc': 'بطاقات الهدايا لدينا لا تنتهي أبداً',
    'giftCards.perfectGift': 'الهدية المثالية',
    'giftCards.perfectGiftDesc': 'دعهم يختارون ما يريدون',
    'giftCards.faq': 'الأسئلة الشائعة',
    'giftCards.faq1': 'كيف أتحقق من رصيد بطاقة الهدايا؟',
    'giftCards.faq1Answer': 'يمكنك التحقق من رصيد بطاقة الهدايا بتسجيل الدخول لحسابك وعرض قسم "رصيد بطاقة الهدايا".',
    'giftCards.faq2': 'هل يمكنني استخدام عدة بطاقات هدايا في طلب واحد؟',
    'giftCards.faq2Answer': 'نعم، يمكنك تطبيق عدة بطاقات هدايا على طلب واحد عند الدفع.',
    'giftCards.faq3': 'هل تنتهي صلاحية بطاقات الهدايا؟',
    'giftCards.faq3Answer': 'لا، بطاقات الهدايا لدينا لا تنتهي صلاحيتها أبداً ولا تحتوي على رسوم.',
    'giftCards.faq4': 'هل يمكنني إعادة شحن بطاقة الهدايا؟',
    'giftCards.faq4Answer': 'نعم، يمكنك إعادة شحن بطاقة الهدايا بأي مبلغ من 1 ج.م إلى 2,000 ج.م.',

    // Registry
    'registry.title': 'سجل الهدايا',
    'registry.subtitle': 'أنشئ سجلك المثالي وشاركه مع أحبائك',
    'registry.createRegistry': 'إنشاء سجل',
    'registry.findRegistry': 'البحث عن سجل',
    'registry.chooseType': 'اختر نوع سجلك',
    'registry.weddingRegistry': 'سجل الزفاف',
    'registry.weddingRegistryDesc': 'ابدأ حياتك الجديدة معاً بهدايا ستحبانها',
    'registry.babyRegistry': 'سجل المولود',
    'registry.babyRegistryDesc': 'استعد لمولودك الصغير بكل ما تحتاجه',
    'registry.birthdayGraduation': 'عيد الميلاد والتخرج',
    'registry.birthdayGraduationDesc': 'احتفل بالإنجازات بالهدايا المثالية',
    'registry.housewarming': 'المنزل الجديد',
    'registry.housewarmingDesc': 'اجعل منزلك الجديد يشعر بالدفء',
    'registry.getStarted': 'ابدأ الآن',
    'registry.firstName': 'الاسم الأول',
    'registry.lastName': 'اسم العائلة',
    'registry.eventDate': 'تاريخ الحدث (اختياري)',
    'registry.searchRegistries': 'البحث في السجلات',
    'registry.popularItems': 'أكثر المنتجات شعبية في السجلات',
    'registry.onRegistries': 'في {count} سجل',
    'registry.whyCreate': 'لماذا تنشئ سجلاً؟',
    'registry.easyToCreate': 'سهل الإنشاء',
    'registry.easyToCreateDesc': 'أنشئ سجلك في دقائق',
    'registry.easyToShare': 'سهل المشاركة',
    'registry.easyToShareDesc': 'شارك مع العائلة والأصدقاء فوراً',
    'registry.groupGifting': 'الهدايا الجماعية',
    'registry.groupGiftingDesc': 'دع عدة أشخاص يساهمون في المنتجات الكبيرة',
    'registry.freeReturns': 'إرجاع مجاني',
    'registry.freeReturnsDesc': 'سياسة إرجاع 90 يوماً لمنتجات السجل',
    'registry.readyToCreate': 'مستعد لإنشاء سجلك؟',
    'registry.readyToCreateDesc': 'يستغرق الأمر دقائق قليلة فقط. أضف منتجات من ملايين المنتجات وشارك مع الأصدقاء والعائلة.',
    'registry.browseProducts': 'تصفح المنتجات',

    // Sell
    'sell.title': 'ابدأ البيع اليوم',
    'sell.subtitle': 'انضم لملايين البائعين ونمِّ عملك مع منصتنا القوية للتجارة الإلكترونية',
    'sell.startSelling': 'ابدأ البيع',
    'sell.learnMore': 'اعرف المزيد',
    'sell.yourStoreYourSuccess': 'متجرك، نجاحك',
    'sell.yourStoreDesc': 'كل ما تحتاجه لبناء وإدارة نشاط تجاري ناجح عبر الإنترنت',
    'sell.statActiveBuyers': 'مشترين نشطين',
    'sell.statSellersWorldwide': 'بائعين حول العالم',
    'sell.statProductsListed': 'منتجات مدرجة',
    'sell.statCustomerSatisfaction': 'رضا العملاء',
    'sell.whySellWithUs': 'لماذا تبيع معنا؟',
    'sell.millionsOfCustomers': 'ملايين العملاء',
    'sell.millionsOfCustomersDesc': 'الوصول لملايين المتسوقين النشطين الباحثين عن منتجات مثل منتجاتك',
    'sell.growYourBusiness': 'نمِّ عملك',
    'sell.growYourBusinessDesc': 'أدوات ورؤى لمساعدتك في توسيع نطاق عملك',
    'sell.easyFulfillment': 'تنفيذ سهل',
    'sell.easyFulfillmentDesc': 'يمكننا التعامل مع التخزين والتعبئة والشحن نيابةً عنك',
    'sell.sellerSupport': 'دعم البائعين',
    'sell.sellerSupportDesc': 'فريق دعم مخصص لمساعدتك على النجاح',
    'sell.choosePlan': 'اختر خطة البيع',
    'sell.individual': 'فردي',
    'sell.professional': 'احترافي',
    'sell.perItemSold': 'لكل منتج مباع',
    'sell.perMonth': 'شهرياً',
    'sell.recommended': 'موصى به',
    'sell.individualFeature1': 'بدون رسوم اشتراك شهرية',
    'sell.individualFeature2': 'ادفع فقط عند البيع',
    'sell.individualFeature3': 'الوصول لأدوات البيع الأساسية',
    'sell.individualFeature4': 'بيع حتى 40 منتجاً شهرياً',
    'sell.professionalFeature1': 'بدون رسوم لكل منتج',
    'sell.professionalFeature2': 'قوائم غير محدودة',
    'sell.professionalFeature3': 'أدوات بيع متقدمة',
    'sell.professionalFeature4': 'قوائم وتقارير مجمعة',
    'sell.professionalFeature5': 'وصول API',
    'sell.professionalFeature6': 'خيارات العرض المميز',
    'sell.howItWorks': 'كيف يعمل',
    'sell.step1Title': 'أنشئ حسابك',
    'sell.step1Desc': 'سجل وقدم معلومات عملك',
    'sell.step2Title': 'أدرج منتجاتك',
    'sell.step2Desc': 'أضف تفاصيل المنتج والصور والأسعار',
    'sell.step3Title': 'ابدأ البيع',
    'sell.step3Desc': 'استلم الطلبات وأدر مخزونك',
    'sell.step4Title': 'احصل على الدفع',
    'sell.step4Desc': 'استلم المدفوعات مباشرة في حسابك البنكي',
    'sell.readyToStart': 'مستعد لبدء البيع؟',
    'sell.createInMinutes': 'أنشئ حساب البائع في دقائق',
    'sell.businessName': 'اسم النشاط التجاري',
    'sell.emailAddress': 'البريد الإلكتروني',
    'sell.phoneNumber': 'رقم الهاتف',
    'sell.productCategory': 'فئة المنتج',
    'sell.selectCategory': 'اختر فئة',
    'sell.electronics': 'الإلكترونيات',
    'sell.fashion': 'الموضة',
    'sell.homeKitchen': 'المنزل والمطبخ',
    'sell.books': 'الكتب',
    'sell.sportsOutdoors': 'الرياضة والأنشطة الخارجية',
    'sell.other': 'أخرى',
    'sell.createSellerAccount': 'إنشاء حساب بائع',
    'sell.termsAgreement': 'بإنشاء حساب، فإنك توافق على شروط الخدمة وسياسة الخصوصية',
    'sell.successStories': 'قصص نجاح البائعين',
    'sell.story1Name': 'بوتيك سارة',
    'sell.story1Quote': 'انتقلت من البيع محلياً إلى الوصول للعملاء في جميع أنحاء البلاد. تضاعفت مبيعاتي ثلاث مرات!',
    'sell.story1Revenue': 'أكثر من 50 ألف ج.م شهرياً',
    'sell.story2Name': 'تك جادجتس برو',
    'sell.story2Quote': 'خدمة التنفيذ وفرت لي الكثير من الوقت. أستطيع التركيز على تنمية خط منتجاتي.',
    'sell.story2Revenue': 'أكثر من 100 ألف ج.م شهرياً',
    'sell.story3Name': 'هوم ستايل ديكور',
    'sell.story3Quote': 'البدء كان سهلاً جداً. خلال أسبوع، حققت أول عملية بيع. الآن هو عملي بدوام كامل!',
    'sell.story3Revenue': 'أكثر من 30 ألف ج.م شهرياً',

    // Orders
    'orders.title': 'طلباتك',
    'orders.noOrders': 'لا توجد طلبات بعد',

    // Account
    'account.title': 'حسابك',
    'account.settings': 'إعدادات الحساب',

    // Lists
    'lists.title': 'قوائمك',
    'lists.noLists': 'لا توجد قوائم بعد',
    'lists.createList': 'إنشاء قائمة',

    // Admin Panel
    'admin.overview': 'نظرة عامة',
    'admin.categories': 'الفئات',
    'admin.products': 'المنتجات',
    'admin.suppliers': 'الموردين',
    'admin.customers': 'العملاء',
    'admin.orders': 'الطلبات',
    'admin.financial': 'الإدارة المالية',
    'admin.homeLayout': 'تخطيط الصفحة الرئيسية',
    'admin.files': 'الملفات',
    'admin.dashboard': 'لوحة التحكم',
    'admin.navMenu': 'قائمة التنقل',
    'admin.store': 'المتجر',
    'admin.exit': 'خروج',
    'admin.loading': 'جاري تحميل لوحة التحكم...',
    'admin.liveUpdate': 'التحديث فعال',
    
    // Admin Dashboard
    'admin.totalOrders': 'إجمالي الطلبات',
    'admin.totalRevenue': 'إجمالي الإيرادات',
    'admin.totalProducts': 'إجمالي المنتجات',
    'admin.totalCustomers': 'إجمالي العملاء',
    'admin.recentOrders': 'الطلبات الأخيرة',
    'admin.recentActivity': 'النشاط الأخير',
    'admin.salesOverview': 'نظرة عامة على المبيعات',
    'admin.viewAll': 'عرض الكل',
    'admin.newOrder': 'طلب جديد',
    'admin.noRecentOrders': 'لا توجد طلبات حديثة',
    'admin.noRecentActivity': 'لا يوجد نشاط حديث',
    
    // Admin Products
    'admin.addProduct': 'إضافة منتج',
    'admin.editProduct': 'تعديل المنتج',
    'admin.productName': 'اسم المنتج',
    'admin.productPrice': 'السعر',
    'admin.productStock': 'المخزون',
    'admin.productCategory': 'الفئة',
    'admin.productSupplier': 'المورد',
    'admin.productDescription': 'الوصف',
    'admin.productImage': 'صورة المنتج',
    'admin.originalPrice': 'السعر الأصلي',
    'admin.costPrice': 'سعر التكلفة',
    'admin.deleteProduct': 'حذف المنتج',
    'admin.confirmDelete': 'هل أنت متأكد من حذف هذا؟',
    
    // Admin Categories
    'admin.addCategory': 'إضافة فئة',
    'admin.editCategory': 'تعديل الفئة',
    'admin.categoryName': 'اسم الفئة',
    'admin.categoryImage': 'صورة الفئة',
    'admin.parentCategory': 'الفئة الأم',
    'admin.noParent': 'بدون أب (مستوى أعلى)',
    
    // Admin Orders
    'admin.orderId': 'رقم الطلب',
    'admin.customer': 'العميل',
    'admin.status': 'الحالة',
    'admin.date': 'التاريخ',
    'admin.amount': 'المبلغ',
    'admin.pending': 'قيد الانتظار',
    'admin.processing': 'قيد المعالجة',
    'admin.shipped': 'تم الشحن',
    'admin.delivered': 'تم التوصيل',
    'admin.cancelled': 'ملغي',
    'admin.orderDetails': 'تفاصيل الطلب',
    'admin.updateStatus': 'تحديث الحالة',
    
    // Admin Suppliers
    'admin.addSupplier': 'إضافة مورد',
    'admin.editSupplier': 'تعديل المورد',
    'admin.supplierName': 'اسم المورد',
    'admin.contactName': 'اسم جهة الاتصال',
    'admin.phone': 'الهاتف',
    'admin.addressLine': 'العنوان',
    
    // Admin Users/Customers
    'admin.userId': 'رقم المستخدم',
    'admin.userName': 'الاسم',
    'admin.userEmail': 'البريد الإلكتروني',
    'admin.role': 'الدور',
    'admin.joinedDate': 'تاريخ الانضمام',
    
    // Admin Financial
    'admin.revenue': 'الإيرادات',
    'admin.expenses': 'المصروفات',
    'admin.netProfit': 'صافي الربح',
    'admin.taxAmount': 'مبلغ الضريبة',
    'admin.currentCycle': 'الدورة الحالية',
    'admin.pastCycles': 'الدورات السابقة',
    'admin.addExpense': 'إضافة مصروف',
    'admin.closeCycle': 'إغلاق الدورة',
    
    // Admin Home Layout
    'admin.homeLayoutTitle': 'إعدادات تخطيط الصفحة الرئيسية',
    'admin.sectionEnabled': 'مفعل',
    'admin.sectionName': 'اسم القسم',
    'admin.showBadge': 'إظهار الشارة',
    'admin.badgeText': 'نص الشارة',
    'admin.manualSelection': 'اختيار يدوي',
    'admin.automaticSelection': 'اختيار تلقائي',
    'admin.selectProducts': 'اختر المنتجات',
    'admin.saveChanges': 'حفظ التغييرات',
    'admin.resetToDefault': 'إعادة للافتراضي',
    
    // Admin Files
    'admin.uploadFile': 'رفع ملف',
    'admin.fileName': 'اسم الملف',
    'admin.fileSize': 'الحجم',
    'admin.fileType': 'النوع',
    'admin.uploadDate': 'تاريخ الرفع',
    'admin.copyUrl': 'نسخ الرابط',
    'admin.deleteFile': 'حذف',
    
    // Common Admin
    'admin.actions': 'الإجراءات',
    'admin.noResults': 'لا توجد نتائج',
    'admin.searchPlaceholder': 'بحث...',
    'admin.itemsPerPage': 'عناصر في الصفحة',
    'admin.showing': 'عرض',
    'admin.of': 'من',
    'admin.save': 'حفظ',
    'admin.cancel': 'إلغاء',
    'admin.create': 'إنشاء',
    'admin.update': 'تحديث',
    'admin.delete': 'حذف',
    'admin.edit': 'تعديل',
    'admin.view': 'عرض',
    'admin.back': 'رجوع',
    
    // Admin Suppliers (extended)
    'admin.suppliersTitle': 'الموردين',
    'admin.suppliersSubtitle': 'إدارة موردي المنتجات والبائعين',
    'admin.totalSuppliers': 'إجمالي الموردين',
    'admin.searchSuppliers': 'البحث عن الموردين...',
    'admin.noSuppliersYet': 'لا يوجد موردين بعد',
    'admin.noSuppliersFound': 'لم يتم العثور على موردين',
    'admin.addFirstSupplier': 'أضف أول مورد للبدء',
    'admin.tryAdjustSearch': 'حاول تعديل البحث',
    'admin.createSupplier': 'إنشاء مورد',
    'admin.updateSupplier': 'تحديث المورد',
    'admin.supplierNameRequired': 'اسم المورد *',
    'admin.contactPerson': 'الشخص المسؤول',
    'admin.loadingSuppliers': 'جاري تحميل الموردين...',
    'admin.noContactInfo': 'لا توجد معلومات اتصال',
    
    // Admin Users (extended)
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.userManagementSubtitle': 'إدارة العملاء والمسؤولين',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.administrators': 'المسؤولين',
    'admin.searchUsers': 'البحث عن المستخدمين...',
    'admin.allUsers': 'كل المستخدمين',
    'admin.admins': 'المسؤولين',
    'admin.user': 'المستخدم',
    'admin.contact': 'الاتصال',
    'admin.location': 'الموقع',
    'admin.noUsersFound': 'لم يتم العثور على مستخدمين',
    'admin.tryAdjustFilters': 'حاول تعديل البحث أو معايير التصفية',
    'admin.editUserProfile': 'تعديل الملف الشخصي',
    'admin.fullName': 'الاسم الكامل',
    'admin.phoneNumber': 'رقم الهاتف',
    'admin.address': 'العنوان',
    'admin.userRole': 'دور المستخدم',
    'admin.administrator': 'مسؤول',
    'admin.loadingUsers': 'جاري تحميل المستخدمين...',
    'admin.unnamedUser': 'مستخدم بدون اسم',
    
    // Admin Financial (extended)
    'admin.financialManagement': 'الإدارة المالية',
    'admin.financialSubtitle': 'إدارة الدورات والمصروفات وتتبع الأرباح.',
    'admin.exportReport': 'تصدير التقرير',
    'admin.startNewCycle': 'بدء دورة جديدة',
    'admin.newExpense': 'مصروف جديد',
    'admin.activeCycle': 'دورة نشطة',
    'admin.noActiveCycle': 'لا توجد دورة نشطة',
    'admin.toPresent': 'حتى الآن',
    'admin.currentRevenue': 'الإيرادات الحالية',
    'admin.currentExpenses': 'المصروفات الحالية',
    'admin.estimatedTax': 'الضريبة المقدرة',
    'admin.payouts': 'المدفوعات',
    'admin.analysis': 'التحليل',
    'admin.recentTransactions': 'المعاملات الأخيرة',
    'admin.viewAllTransactions': 'عرض الكل',
    'admin.expenseLog': 'سجل المصروفات',
    'admin.expenseLogDesc': 'عرض تفصيلي لجميع المصروفات التشغيلية.',
    'admin.loadExpenseDashboard': 'تحميل لوحة المصروفات',
    'admin.supplierPayouts': 'مدفوعات الموردين',
    'admin.supplierPayoutsDesc': 'إدارة واعتماد المدفوعات للموردين.',
    'admin.viewPayoutStatus': 'عرض حالة المدفوعات',
    'admin.previousCycles': 'الدورات السابقة',
    'admin.profit': 'الربح',
    'admin.rev': 'الإيرادات',
    'admin.viewAllHistory': 'عرض كل السجل',
    'admin.cycleControls': 'التحكم بالدورات',
    'admin.closeCurrentCycle': 'إغلاق الدورة الحالية',
    'admin.financialProjection': 'التوقعات المالية',
    'admin.manageTaxSlabs': 'إدارة شرائح الضرائب',
    'admin.loadingFinancial': 'جاري تحميل السجلات المالية...',
    'admin.margin': 'الهامش',
    
    // Admin Categories Page
    'admin.availableCategories': 'الفئات المتاحة',
    'admin.totalCategories': 'إجمالي الفئات',
    'admin.withProducts': 'تحتوي منتجات',
    'admin.empty': 'فارغة',
    'admin.noDescription': 'لا يوجد وصف',
    'admin.noCategoriesFound': 'لم يتم العثور على فئات',
    'admin.tryAdjustingSearch': 'حاول تعديل كلمات البحث',
    'admin.getStartedCategories': 'ابدأ بإضافة فئتك الأولى',
    'admin.addFirstCategory': 'إضافة أول فئة',
    'admin.deleteCategory': 'حذف الفئة',
    'admin.deleteCategoryConfirm': 'هل أنت متأكد من حذف هذه الفئة؟ المنتجات في هذه الفئة ستصبح بدون فئة.',
    'admin.categoryNameRequired': 'الاسم *',
    'admin.nameInEnglish': 'الاسم بالإنجليزية',
    'admin.nameInArabic': 'الاسم بالعربية',
    'admin.basicInformation': 'المعلومات الأساسية',
    'admin.translations': 'الترجمات',
    'admin.descriptionInArabic': 'الوصف بالعربية',
    'admin.selectCategory': 'اختر فئة...',
    'admin.optionalDescription': 'وصف اختياري',
    'admin.chooseFile': 'اختر ملف',
    'admin.takePhoto': 'التقط صورة',
    'admin.pasteImageUrl': 'أو الصق رابط الصورة:',
    
    // Admin Home Layout (extended)
    'admin.visibilityControl': 'التحكم في الظهور',
    'admin.visibilityControlDesc': 'استخدم المفاتيح أدناه لإخفاء أو إظهار أقسام معينة في صفحتك الرئيسية. هذا مفيد لإفساح المجال خلال فترات العروض أو إزالة الأقسام التي لا تحتوي على منتجات بعد.',
    'admin.countdownBadge': 'شارة العد التنازلي',
    'admin.manualProductSelection': 'اختيار المنتجات يدوياً',
    'admin.enabled': 'مفعل',
    'admin.disabled': 'معطل',
    'admin.manual': 'يدوي',
    'admin.automatic': 'تلقائي',
    'admin.selectProductsToFeature': 'اختر منتجات محددة لعرضها في هذا القسم.',
    'admin.selectProductsForBrowsing': 'اختر منتجات محددة لعرضها كتوصيات التصفح.',
    'admin.selectProductsForTrending': 'اختر منتجات محددة لعرضها كمنتجات رائجة.',
    'admin.selectProductsForAccessories': 'اختر منتجات محددة لعرضها كملحقات الكمبيوتر.',
    'admin.searchProducts': 'البحث عن المنتجات...',
    'admin.noProductsFound': 'لم يتم العثور على منتجات',
    'admin.autoShowsDiscounted': 'يعرض تلقائياً جميع المنتجات المخفضة (السعر الأصلي > السعر الحالي).',
    'admin.autoShowsFirst10': 'يعرض تلقائياً أول 10 منتجات كتوصيات.',
    'admin.autoShowsOver50': 'يعرض تلقائياً المنتجات بسعر أكثر من 50 جنيه.',
    'admin.autoShowsPeripherals': 'يعرض تلقائياً المنتجات التي تحتوي فئتها على ماوس أو كيبورد أو سماعات.',
    'admin.subtitleText': 'نص العنوان الفرعي',
    'admin.buttonText': 'نص الزر',
    'admin.visible': 'مرئي',
    'admin.hidden': 'مخفي',
    'admin.autoSyncingReady': 'المزامنة التلقائية جاهزة',
    'admin.realTimeUpdates': 'تحديثات فورية',
    'admin.versioning': 'الإصدار',
    'admin.sectionDescription': 'وصف القسم',
    'admin.enterBadgeText': 'أدخل نص الشارة (مثل: ينتهي في 12:34:56)',
    'admin.enterSubtitleText': 'أدخل نص العنوان الفرعي',
    'admin.enterButtonText': 'أدخل نص الزر',
};

const translations: Record<Language, Record<string, string>> = { en, ar };

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        return (saved === 'ar' || saved === 'en') ? saved : 'en';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    const formatCurrency = (amount: number): string => {
        const formattedNumber = amount.toLocaleString(language === 'ar' ? 'ar-EG' : 'en-EG');
        if (language === 'ar') {
            return `${formattedNumber} ج.م`;
        }
        return `E£${formattedNumber}`;
    };

    const isRTL = language === 'ar';

    // Apply RTL direction to document
    useEffect(() => {
        document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [isRTL, language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, formatCurrency }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
